Einfacheres Starten der Starter.jar
Dungeon-CampusMinden/Dungeon pull request #1343
Opened 2024-01-17 14:13 UTC by tgrothe

may fixes #1326

2024-01-17 14:16 UTC, tgrothe commented
Es funktioniert bei mir. Der Dialog wird aufgerufen, bevor das Dungeon, LibGdx usw. startet.

2024-01-18 11:57 UTC, AMatutat reviewed
Das if-else Konstrukt sah unnötig verwirrend aus,
hab mal versucht das flott zusammen zu fassen. 
Nochmal kritisch angucken

2024-01-18 11:57 UTC, AMatutat commented on dungeon/src/starter/Starter.java
> +    String dngPath = null;
```suggestion
 Set<DSLEntryPoint> entryPoints;
```

2024-01-18 11:57 UTC, AMatutat commented on dungeon/src/starter/Starter.java
> +    Set<DSLEntryPoint> entryPoints;
```suggestion
```

2024-01-18 11:57 UTC, AMatutat commented on dungeon/src/starter/Starter.java
> +      dngPath = DngJFileChooser.selectSingleDngFile();
```suggestion
       entryPoints = processCLIArguments(new String[] {DngJFileChooser.selectSingleDngFile()});
```

2024-01-18 11:57 UTC, AMatutat commented on dungeon/src/starter/Starter.java
> +    }
```suggestion
 else {
  // read in the default command line arguments
   entryPoints = processCLIArguments(args);
 }
```

2024-01-18 12:43 UTC, tgrothe commented
> Das if-else Konstrukt sah unnötig verwirrend aus, hab mal versucht das flott zusammen zu fassen. Nochmal kritisch angucken

Hallo Andre, kannst du den Code noch einmal hier posten (nicht als Suggestion)?

Ich kann so nicht erkennen, was geändert werden soll...

Aber die Abfrage (Öffnungsdialog) soll ja nur erscheinen, wenn args vergessen wurde, nicht immer.

2024-01-18 14:42 UTC, tgrothe commented
> > Ich kann so nicht erkennen, was geändert werden soll...
> 
> @tgrothe die roten bereiche der suggestion werden entfernt, die grünen bereiche hinzugefügt.

das ist mir eigentlich klar... aber es wurden 4 einzelne suggestions hinzugefügt, anstatt einem.

ich hab intellij nicht mit github verknüpft und kann mir die änderungen deshalb nicht vorher ansehen.

aber ich kann es übernehmen, und kann es ja ggf. wieder zurücksetzen.

2024-01-18 14:47 UTC, tgrothe commented
Es stürzt jetzt mit einer `NPE` ab, wenn man auf Abbrechen klickt.

Ist das so gewollt? @cagix @AMatutat

2024-01-18 15:12 UTC, cagix commented
> Es stürzt jetzt mit einer `NPE` ab, wenn man auf Abbrechen klickt.
> 
> Ist das so gewollt? @cagix @AMatutat

nee. wenn "abbrechen" und keine datei beim start angegeben, dann sollte sich das ding "freundlich" beenden, aber nicht abstürzen oder sich mit nem stacktrace beenden.

2024-01-18 18:07 UTC, cagix requested changes
@tgrothe Im Prinzip sollte der Code funktionieren (habs nicht getestet). Was ich nicht so schön finde, ist (a) der Code-Clutter im `main` und (b) die extra Klasse mit einer einzigen Methode.

Kannst Du bitte den ganzen neuen Kram in `main()` in eine eigene Methode verpacken, so dass da stattdessen die Zeilen `Set<DSLEntryPoint> entryPoints; entryPoints = processArguments(args);` übrig bleiben?

In der neuen Methode `processArguments` machst Du dann den Aufruf `if (args.length > 0) { args = selectSingleDngFile(); }`. Danach kommt dann ein `return processCLIArguments(args);`.

Den Code aus der extra Klasse dann bitte nach `selectSingleDngFile` in `Starter.java` verschieben. Dummerweise müssten wir ein `String[]` zurückliefern, damit mein Vorschlag passt. Falls nix ausgewählt wurde oder "Abbrechen" geklickt wurde, wird ein leeres Array zurück geliefert (damit es zu `processCLIArguments` passt). 

Um das `entryPoints = processArguments(args);` herum kannst Du ein `try/catch` machen und im `catch`-Fall ein `System.exit(-1);`.

---

Eigentlich sollte man mit `Option` arbeiten und die Signatur von `processCLIArguments` anpassen. Aber dazu bin ich jetzt zu müde.

2024-01-20 10:38 UTC, tgrothe commented
@cagix Schaust du bitte noch einmal, ob es jetzt den Vorstellungen entspricht... Danke.

2024-01-20 11:29 UTC, cagix reviewed
@tgrothe das nenne ich doch mal fest fertig 👍 

von hier aus würde ich gern noch die parameter von processarguments und processcliarguments nach `List<String>` ändern, d.h. beim aufruf in zeile 144 müsste es dann `processArguments(Array.asList(args))` sein.

2024-01-20 11:34 UTC, cagix commented
@tgrothe und gibt es einen grund, warum du die neuen funktionen über das main eingebaut hast und nicht unten zum bestehenden processcliarguments gepackt hast?

2024-01-20 11:59 UTC, tgrothe commented
> @tgrothe und gibt es einen grund, warum du die neuen funktionen über das main eingebaut hast und nicht unten zum bestehenden processcliarguments gepackt hast?

Hmm, eigentlich hatte ich mir über die Reihenfolge keine weiteren Gedanken gemacht, und die "default" Reihenfolge genommen, also die main unten und alle weiteren Methoden darüber. Aber dann verschiebe ich das an die richtige Stelle.

2024-01-20 12:10 UTC, cagix commented
> > @tgrothe und gibt es einen grund, warum du die neuen funktionen über das main eingebaut hast und nicht unten zum bestehenden processcliarguments gepackt hast?
> 
> 
> 
> Hmm, eigentlich hatte ich mir über die Reihenfolge keine weiteren Gedanken gemacht, und die "default" Reihenfolge genommen, also die main unten und alle weiteren Methoden darüber. Aber dann verschiebe ich das an die richtige Stelle.

das macht sinn, und wäre auch ok. ich würde es nur nicht gern so gesplittet haben wollen, wie es jetzt ist.

macht spotless dazu keine vorgaben? intellij hat eine meinung dazu ...

2024-01-20 12:16 UTC, tgrothe commented
> > > @tgrothe und gibt es einen grund, warum du die neuen funktionen über das main eingebaut hast und nicht unten zum bestehenden processcliarguments gepackt hast?
> > 
> > 
> > Hmm, eigentlich hatte ich mir über die Reihenfolge keine weiteren Gedanken gemacht, und die "default" Reihenfolge genommen, also die main unten und alle weiteren Methoden darüber. Aber dann verschiebe ich das an die richtige Stelle.
> 
> das macht sinn, und wäre auch ok. ich würde es nur nicht gern so gesplittet haben wollen, wie es jetzt ist.
> 
> macht spotless dazu keine vorgaben? intellij hat eine meinung dazu ...

Achso, du meinst die Grouping Rules unter Arrangements ... https://www.jetbrains.com/help/idea/rearrange-code.html#configure-rules

Darf ich das in der Starter.java in die "breath-first order" ändern?

Ich glaube ... Spotless hat, bis auf die Reihenfolge der imports, dazu keine Meinung.

2024-01-20 12:43 UTC, cagix commented
schade. spotless wäre eine schöne zentrale stelle, um ein einheitliches vorgehen zu gewährleisten.

mir ist die reihenfolge der methoden prinzipiell egal. es sollte nur einheitlich sein, damit der code nicht aussieht wie hulle und sich am ende niemand mehr damit beschäftigen möchte. allerdings sollte das dann eben auch für alle dateien gelten, nicht nur für den starter.

für diesen pr: bitte mache deine änderungen minimalinvasiv. mein vorschlag wäre, dass du deine beiden neuen methoden vor oder nach der bestehenden methode processcliarguments unterbringst.

2024-01-20 12:53 UTC, tgrothe commented
> für diesen pr: bitte mache deine änderungen minimalinvasiv. mein vorschlag wäre, dass du deine beiden neuen methoden vor oder nach der bestehenden methode processcliarguments unterbringst.

Hab ich jetzt auch so gemacht (minimalinvasiv (bis auf `List<String>`)) ... Aber ich habe für die `Starter.java` einmal die Methodenreihenfolge geändert ... Es sollte also nicht ganz so wie Kraut und Rüben sein

Meine Einstellungen in IntelliJ:

![grafik](https://github.com/Programmiermethoden/Dungeon/assets/85501570/c91d725b-2ffa-4b4a-b66f-018b9c5c2d53)

2024-01-20 13:47 UTC, cagix commented
> > für diesen pr: bitte mache deine änderungen minimalinvasiv. mein vorschlag wäre, dass du deine beiden neuen methoden vor oder nach der bestehenden methode processcliarguments unterbringst.
> 
> Hab ich jetzt auch so gemacht (minimalinvasiv (bis auf `List<String>`)) ... Aber ich habe für die `Starter.java` einmal die Methodenreihenfolge geändert ... Es sollte also nicht ganz so wie Kraut und Rüben sein
> 

ok, vielleicht habe ich mich wirklich unklar ausgedrückt. was ich mit minimalinvasiv meinte: bitte in diesem pr so wenig wie möglich änderungen im code, also insbesondere keine umformatierungen! nur die erforderlichen änderungen/ergänzungen, also deine neuen methoden in die nähe der vorhandenen processcliargs-methode sowie die api-änderungen einbauen. 

das formatieren müssen wir nochmal separat diskutieren und dann über die gesamte codebasis machen.

2024-01-22 11:37 UTC, cagix commented
@tgrothe Der Code sieht vernünftig aus. Unter macOS startet der Starter, wenn ich ihm die Parameter mitgebe (auch aus dem Jar heraus). Aber wenn ich keine Parameter gebe, hängt es - die neue GUI wird nicht angezeigt.

2024-01-22 12:00 UTC, tgrothe commented
> @tgrothe Der Code sieht vernünftig aus. Unter macOS startet der Starter, wenn ich ihm die Parameter mitgebe (auch aus dem Jar heraus). Aber wenn ich keine Parameter gebe, hängt es - die neue GUI wird nicht angezeigt.

Kommt da zufällig die Meldung `Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical`? Dann liegt es an #1344 

Wie ist das mit `-XstartOnFirstThread`? Gleiches Verhalten?

Ich bin da etwas ratlos.

2024-01-22 12:12 UTC, cagix commented
ich glaube, dass ist, was @AMatutat oben schon mal angemerkt hatte. afaik nutzt swing nochmal einen eigenen thread - und dann geht irgendwas bei der übergabe schief. 

ich bin nicht sicher, wie wir von hier weitermachen. 

- eine möglichkeit wäre, den code drin zu lassen und zu dokumentieren, dass es nur für win/linux so funktioniert und für macos bitte die dng-datei beim start angegeben werden. aber irgendwie ist das auch unbefriedigend.
- eine andere möglichkeit wäre, den code raus zu lassen. aber auch das ist unbefriedigend.
- eine dritte möglichkeit wäre, libgdx zu nutzen und eine art hud einzublenden, wo die auswahl gemacht wird?

2024-01-22 12:14 UTC, cagix commented
> > @tgrothe Der Code sieht vernünftig aus. Unter macOS startet der Starter, wenn ich ihm die Parameter mitgebe (auch aus dem Jar heraus). Aber wenn ich keine Parameter gebe, hängt es - die neue GUI wird nicht angezeigt.
> 
> Kommt da zufällig die Meldung `Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical`? Dann liegt es an #1344
> 
> Wie ist das mit `-XstartOnFirstThread`? Gleiches Verhalten?
> 
> Ich bin da etwas ratlos.
> 
> Edit: Bitte einmal testen: `java -XstartOnFirstThread -jar build/libs/Starter.jar`

den schalter hatte ich aktiv - im build.gradle steht er ja eh drin, und auf der konsole hatte ich das mit angegeben.

es kommt einfach gar nix. keine fehlermeldung, aber auch kein fenster.

2024-01-22 12:17 UTC, tgrothe commented
> ich glaube, dass ist, was @AMatutat oben schon mal angemerkt hatte. afaik nutzt swing nochmal einen eigenen thread - und dann geht irgendwas bei der übergabe schief.
> 
> ich bin nicht sicher, wie wir von hier weitermachen.
> 
>     * eine möglichkeit wäre, den code drin zu lassen und zu dokumentieren, dass es nur für win/linux so funktioniert und für macos bitte die dng-datei beim start angegeben werden. aber irgendwie ist das auch unbefriedigend.
> 
>     * eine andere möglichkeit wäre, den code raus zu lassen. aber auch das ist unbefriedigend.
> 
>     * eine dritte möglichkeit wäre, libgdx zu nutzen und eine art hud einzublenden, wo die auswahl gemacht wird?

hm, mich würde interessieren, was @AMatutat dazu sagt...

bei der dritten möglichkeit bin ich nicht sicher, inwieweit eine dng-datei im dungeon "dynamisch nachgeladen" werden kann... das klingt nach einer umfangreichen änderung.

2024-01-22 13:49 UTC, cagix commented
> > ich glaube, dass ist, was @AMatutat oben schon mal angemerkt hatte. afaik nutzt swing nochmal einen eigenen thread - und dann geht irgendwas bei der übergabe schief.
> > ich bin nicht sicher, wie wir von hier weitermachen.
> > ```
> > * eine möglichkeit wäre, den code drin zu lassen und zu dokumentieren, dass es nur für win/linux so funktioniert und für macos bitte die dng-datei beim start angegeben werden. aber irgendwie ist das auch unbefriedigend.
> > 
> > * eine andere möglichkeit wäre, den code raus zu lassen. aber auch das ist unbefriedigend.
> > 
> > * eine dritte möglichkeit wäre, libgdx zu nutzen und eine art hud einzublenden, wo die auswahl gemacht wird?
> > ```
> 
> hm, mich würde interessieren, was @AMatutat dazu sagt...
> 
> bei der dritten möglichkeit bin ich nicht sicher, inwieweit eine dng-datei im dungeon "dynamisch nachgeladen" werden kann... das klingt nach einer umfangreichen änderung.

noch eine weitere möglichkeit wäre, dass man einen starter hat, der die sache mit den argumenten macht und dann den normalen starter (wo man die datei auf der cmd-line angeben muss) als **neuen externen prozess** startet. 

ist aber ziemlich von hinten am ohr gekrault.

2024-01-22 20:15 UTC, tgrothe commented
> > > @tgrothe Der Code sieht vernünftig aus. Unter macOS startet der Starter, wenn ich ihm die Parameter mitgebe (auch aus dem Jar heraus). Aber wenn ich keine Parameter gebe, hängt es - die neue GUI wird nicht angezeigt.
> > 
> > 
> > Kommt da zufällig die Meldung `Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical`? Dann liegt es an #1344
> > Wie ist das mit `-XstartOnFirstThread`? Gleiches Verhalten?
> > Ich bin da etwas ratlos.
> > Edit: Bitte einmal testen: `java -XstartOnFirstThread -jar build/libs/Starter.jar`
> 
> den schalter hatte ich aktiv - im build.gradle steht er ja eh drin, und auf der konsole hatte ich das mit angegeben.
> 
> es kommt einfach gar nix. keine fehlermeldung, aber auch kein fenster.

@cagix Versuchst du es jetzt noch einmal bitte? :)

2024-01-22 20:39 UTC, cagix commented
@tgrothe danke für die recherche. in deinen links sehe ich noch nicht so richtig eine erklärung (und auch keine lösung) für das problem? 

swing an sich brauchte afaik auf dem mac keine seltsamen optionen, hatte letztes jahr ja noch ein paar beispiele gebastelt... das muss irgendwie im zusammenhang mit libgdx kommen?

2024-01-22 20:50 UTC, tgrothe commented
> @tgrothe danke für die recherche. in deinen links sehe ich noch nicht so richtig eine erklärung (und auch keine lösung) für das problem? 
> 

das war nur eine (vage) Vermutung von mir, ob es daran liegen könnte...

> swing an sich brauchte afaik auf dem mac keine seltsamen optionen, hatte letztes jahr ja noch ein paar beispiele gebastelt... das muss irgendwie im zusammenhang mit libgdx kommen?

das könnte sein, ich werde nochmal danach suchen

2024-01-23 09:37 UTC, cagix commented
> @cagix Versuchst du es jetzt noch einmal bitte? :)

nope. tut nix. 

ich schätze, da kommt trotz des parameters `-XstartOnFirstThread` nicht das richtige auf dem ersten thread an.

interessanterweise kann ich meine reinen swing-sachen in pm (beispielsweise https://github.com/Programmiermethoden/PM-Lecture/blob/master/markdown/gui/src/widgets/DemoStarter.java) direkt starten, ohne irgendwas. das muss wirklich aus libgdx oder tiefer kommen.

2024-01-23 10:15 UTC, cagix commented
@tgrothe interessante diskussion: https://stackoverflow.com/questions/19479877/jfilechooser-in-libgdx#19534947

den vorschlag mit dem thread (https://stackoverflow.com/a/43043154) habe ich ausprobiert. dabei erscheint das libgdx-fenster und davor der filechooser-dialog. ich kann darin was auswählen und den dialog beenden. aber das libgdx-fenster ist und bleibt schwarz. irgendwie scheint die kontrolle nicht zurückgegeben zu werden.

2024-01-23 11:45 UTC, tgrothe commented
> > @cagix Versuchst du es jetzt noch einmal bitte? :)
> 
> nope. tut nix.
> 
> ich schätze, da kommt trotz des parameters `-XstartOnFirstThread` nicht das richtige auf dem ersten thread an.
> 
> interessanterweise kann ich meine reinen swing-sachen in pm (beispielsweise https://github.com/Programmiermethoden/PM-Lecture/blob/master/markdown/gui/src/widgets/DemoStarter.java) direkt starten, ohne irgendwas. das muss wirklich aus libgdx oder tiefer kommen.

Hmm, schade... es hätte ja auch "einfach" sein können. :D Leider weiß ich nicht, woran das sonst liegen könnte.

> @tgrothe interessante diskussion: https://stackoverflow.com/questions/19479877/jfilechooser-in-libgdx#19534947
> 
> den vorschlag mit dem thread (https://stackoverflow.com/a/43043154) habe ich ausprobiert. dabei erscheint das libgdx-fenster und davor der filechooser-dialog. ich kann darin was auswählen und den dialog beenden. aber das libgdx-fenster ist und bleibt schwarz. (beim random-starter wird zwar noch was angezeigt, aber da bewegt sich nix mehr.)
> 
> irgendwie scheint die kontrolle nicht zurückgegeben zu werden.
> 
> https://jvm-gaming.org/t/libgdx-scene2d-ui-filechooser-dialog/53228 https://tommyettinger.github.io/gdx-utils/libgdx-utils/apidocs/net/dermetfan/gdx/scenes/scene2d/ui/FileChooser.html

der letzte link (FileChooser von libgdx) und das beispiel gefällt mir gut. dann könnte man das direkt im spiel unterbringen und hätte nichts zusätzliches, und es würde dann auch mit mac funktionieren.

soll ich mal versuchen, das im wizard-dialog (im starter-room) unterzubringen? also... wenn keine args angegeben wurden, dann fragt der wizard nach einer dng-datei?

2024-01-23 13:29 UTC, cagix commented
kannst ja mal probieren, einen schnellen dummy einzubauen. wenn das bei mir läuft, könnten wir das ausbauen und funktionsfähig machen.

2024-01-23 13:52 UTC, AMatutat commented
Ist meine Meinung hier noch wichtig? 


Meine Glocke explodiert ja wieder.....

2024-01-23 15:48 UTC, tgrothe commented
> Ist meine Meinung hier noch wichtig? 
> 
> 
> Meine Glocke explodiert ja wieder.....

Ach, das ist doch nun zu einem Stapel oder Ablagefach geworden... ;)

Werde versuchen, defragmentierter zu kommentieren (und in kleinerer Frequenz).

> kannst ja mal probieren, einen schnellen dummy einzubauen. wenn das bei mir läuft, könnten wir das ausbauen und funktionsfähig machen.

Das würde ich angehen und danach kannst du gerne reviewen, aber atm ist keine Hilfe benötigt (hoffe ich :)). Falls doch, sag ich Bescheid.

2024-01-24 17:21 UTC, cagix commented
> Mit debian 12 und Xfce funktioniert es, sowohl mit `invokeLater` als auch "normal".
> 
> 
> 
> @cagix Kannst du noch einmal genau das Verhalten beschreiben, was beim Mac passiert? Der FileChooser öffnet sich kurz, aber irgendwie auch nicht? Hast du es mal mit/ohne `-XstartOnFirstThread` bzw. mit/ohne `sudo` getestet?
> 
> 
> 
> ---
> 
> 
> 
> Ich hätte noch eine Idee, `Gdx.app.postRunnable` anstatt `invokeLater`:
> 
> 
> 
> https://stackoverflow.com/questions/21253405/how-to-put-properly-a-libgdx-application-inside-swing-application
> 
> 
> 
> https://libgdx.com/wiki/app/threading

siehe oben. 

bei der letzten variante kommt das dungeon-fenster und darüber der filechooser. letzter ist funktionsfähig, d.h. ich kann was auswählen oder auch nicht und den chooser schließen. aber das dungeon-fenster scheint den thread danach nicht zu bekommen, es "klemmt" einfach und reagiert nicht. 

ich muss das mit der option starten. ohne gibt es nur eine fehlermeldung mit dem "auf  dem ersten thread starten du musst ".

2024-01-24 17:53 UTC, tgrothe commented
@cagix Bitte noch einmal mit 4e960cf testen. Danke. :)

2024-01-25 09:11 UTC, cagix commented
> @cagix Bitte noch einmal mit [4e960cf](https://github.com/Programmiermethoden/Dungeon/commit/4e960cf64f1df543a693ec3927d1a09da8d020a1) testen. Danke. :)
> 
> Edit: [4e652fc](https://github.com/Programmiermethoden/Dungeon/commit/4e652fceae603cc08a6f0d7946ca76272c5c3db8)

@tgrothe ich musste mir dein repo auschecken, weil dein branch outdated ist und ich das nicht auf `master` auschecken konnte. jedenfalls passiert jetzt gar nichts mehr, nichtmal der filechooser kommt hoch.

2024-01-25 09:25 UTC, tgrothe commented
> > @cagix Bitte noch einmal mit [4e960cf](https://github.com/Programmiermethoden/Dungeon/commit/4e960cf64f1df543a693ec3927d1a09da8d020a1) testen. Danke. :)
> > Edit: [4e652fc](https://github.com/Programmiermethoden/Dungeon/commit/4e652fceae603cc08a6f0d7946ca76272c5c3db8)
> 
> @tgrothe ich musste mir dein repo auschecken, weil dein branch outdated ist und ich das nicht auf `master` auschecken konnte. jedenfalls passiert jetzt gar nichts mehr, nichtmal der filechooser kommt hoch.

Moin, ich aktualisiere den pr mal gerade, einen moment...

2024-01-25 09:30 UTC, tgrothe commented
> > @cagix Bitte noch einmal mit [4e960cf](https://github.com/Programmiermethoden/Dungeon/commit/4e960cf64f1df543a693ec3927d1a09da8d020a1) testen. Danke. :)
> > Edit: [4e652fc](https://github.com/Programmiermethoden/Dungeon/commit/4e652fceae603cc08a6f0d7946ca76272c5c3db8)
> 
> @tgrothe ich musste mir dein repo auschecken, weil dein branch outdated ist und ich das nicht auf `master` auschecken konnte. jedenfalls passiert jetzt gar nichts mehr, nichtmal der filechooser kommt hoch.

Ok, aber das ist schade, dann kann das os tatsächlich nicht mit einer libgdx und Swing/AWT Anwendung gleichzeitig umgehen, anscheinend... Danke fürs Testen.

2024-01-25 09:34 UTC, tgrothe commented
@cagix Oder bekommt eine Java-Anwendung beim Starten auf dem Mac noch irgendwelche "unsichtbaren" Argumente mit, also anders als bei den anderen System? Also wäre das args-Array dann nicht leer? Vermutlich nicht, aber lieber einmal fragen.^^

2024-01-25 10:09 UTC, cagix commented
ich hab keine ahnung, was da läuft. es geht so jedenfalls nicht.

2024-01-25 10:16 UTC, cagix commented
@tgrothe ich habe auch langsam keine lust mehr auf dieses projekt. es ist alles nur bruchstückhaft dokumentiert (wenn überhaupt), insbesondere die schnittstellen richtung libgdx und die funktionalen zusammenhänge sind gar nicht dokumentiert. alles muss man mühsam erst selbst aus dem code rauspfriemeln. und jede änderung steht wieder vor dem problem, ob danach noch alles geht ... das ist mir echt zu anfällig, so viel zeit hab ich nicht. vielleicht ist es zeit, auf was anderes umzusteigen.

2024-01-25 12:08 UTC, cagix commented
> @cagix Wenn es nicht geht, dann geht es nicht und ein File-Chooser kann nicht umgesetzt werden (zumindest nicht für Mac-Leute). Ich wollte auch keine Zeit stehlen. ... Aber was meinst du mit etwas Anderem?

@tgrothe Je mehr ich versuche, aktiv was mit diesem Projekt zu machen, um so frustrierter lässt es mich zurück. Es macht insgesamt einen ziemlich ungepflegten Eindruck - sei es Codestrukturen, die übermäßig komplex sind, oder Dokumentation, die bruchstückhaft bzw. nicht vorhanden ist, oder einfache Konfigurationen, über die scheinbar niemand mehr als die Sekunde für Copy&Paste nachgedacht hat, oder ... @AMatutat sagt immer, das sei sein "Baby", aber es ist irgendwie etwas ohne Kopf und dafür mit drei Beinen (übertragen gesprochen). Es kostet mich unglaublich viel Zeit, die notwendigen Dinge zu verstehen und anzupassen - da kann ich dann auch ein anderes, professionell(er) entwickeltes Projekt nehmen, dort funktioniert dann wenigstens alles und sieht nicht ganz so hausbacken aus.

2024-01-25 12:20 UTC, tgrothe commented
@cagix Ja, mir ist das auch schon aufgefallen, zum Beispiel bei dieser Ümläuts-Pfad-Geschichte... Manche Sachen sind vielleicht unnötigerweise zu kompliziert/komplex geschrieben worden, und man "findet nicht mehr wirklich auf Anhieb durch", da zum Teil nicht oder nur zu kompliziert dokumentiert wurde. Aber es ist vielleicht nicht sinnvoll, das jetzt alles in diesem PR zu besprechen. Hmmm (leise seufzend).

2024-01-25 12:23 UTC, AMatutat commented
@cagix Nenn mein Baby nicht ungepflegt.... Mit drei Beinen rennt es sich besser.

Ich glaube über den Rest haben wir schon des öfteren gesprochen, dazu fehlt mir mittlerweile der Atem um nochmal drüber zu sprechen.


>  da kann ich dann auch ein anderes, professionell(er) entwickeltes Projekt nehmen, dort funktioniert dann wenigstens alles und sieht nicht ganz so hausbacken aus.

Gib mal Link.

2024-01-25 12:54 UTC, tgrothe commented
@cagix @AMatutat hier kann bitte zu, in #1365 geht es weiter (dann kann ich meinen fork schließen).

2024-01-25 12:54 UTC, closed without merging