Tg/dng select
Dungeon-CampusMinden/Dungeon pull request #1365
Opened 2024-01-25 12:51 UTC by tgrothe

tbd

2024-01-28 10:17 UTC, tgrothe commented
@cagix Vielleicht geht es jetzt?

Ich hab das hier gefunden

![grafik](https://github.com/Dungeon-CampusMinden/Dungeon/assets/85501570/a3dae9f8-66d4-4367-b13b-cc94b92689ba)

https://libgdx.com/news/2022/05/gdx-1-11

2024-01-28 15:06 UTC, cagix commented
der kommentar ist von 2022? krass. d.h. das sollte dann mal längst nicht mehr "experimentell" sein? ... ich probiere das morgen mal aus.

2024-01-29 10:01 UTC, tgrothe commented
> der kommentar ist von 2022? krass. d.h. das sollte dann mal längst nicht mehr "experimentell" sein? ... ich probiere das morgen mal aus.

wäre interessant, ob es damit klappt und ich diesen pfad weiterverfolgen kann... laut plot müsste nur diese eine dependency hinzugefügt werden... 😀

2024-01-30 09:08 UTC, tgrothe commented
Erde an @cagix , hat das funktioniert? 😉 Ich frage nur, weil ich ja keinen Mac hab.

2024-02-01 08:54 UTC, tgrothe commented
@cagix Wir returnen in der neuen Methode ja nur einen String, aber für Listen sollte man Optional nicht verwenden. Siehe [Brian Goetz](https://stackoverflow.com/a/26328555).

Das heißt, vielleicht wäre es sinnvoll, direkt `List<String>` anstatt `Optional<String>` zu verwenden, auch, wenn die Liste nur ein Elem hätte?

2024-02-01 09:18 UTC, cagix commented
Wenn wir nur einen String berechnen, warum liefern wir dann überhaupt ne Liste zurück? Versteh ich grad nicht. 

PS: Und wenn ich in der Mail auf den Link klicke, finde ich die Diskussion nicht auf GH? Hast Du den Kommentar wieder gelöscht?


> On 1. Feb 2024, at 09:54, Tobias Grothe ***@***.***> wrote:
> 
> 
> @cagix Wir returnen in der neuen Methode ja nur einen String, aber für Listen sollte man Optional nicht verwenden. Siehe Brian Goetz.
> Das heißt, vielleicht wäre es sinnvoll, direkt List<String> anstatt Optional<String> zu verwenden, auch, wenn die Liste nur ein Elem hätte?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-02-01 09:29 UTC, tgrothe commented
> Wenn wir nur einen String berechnen, warum liefern wir dann überhaupt ne Liste zurück? Versteh ich grad nicht. PS: Und wenn ich in der Mail auf den Link klicke, finde ich die Diskussion nicht auf GH? Hast Du den Kommentar wieder gelöscht?
> […](#)
> On 1. Feb 2024, at 09:54, Tobias Grothe ***@***.***> wrote: @cagix Wir returnen in der neuen Methode ja nur einen String, aber für Listen sollte man Optional nicht verwenden. Siehe Brian Goetz. Das heißt, vielleicht wäre es sinnvoll, direkt List<String> anstatt Optional<String> zu verwenden, auch, wenn die Liste nur ein Elem hätte? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Ja, tut mir leid, ich dachte, mein Kommentar wäre hier unpassend gewesen.

Das war ein Link zu einer [Stackoverflow-Diskussion](https://stackoverflow.com/questions/26327957/should-java-8-getters-return-optional-type) gewesen.

> Wenn wir nur einen String berechnen, warum liefern wir dann überhaupt ne Liste zurück?

Ich dachte, falls wir irgendwann mehrere dng files brauchen, oder weil wir später ohnehin eine Liste mit nur einem Elem brauchen...

2024-02-01 10:43 UTC, tgrothe commented
> (2) "ohnehin eine Liste mit nur einem Elem": naja, dann ist Deine Frage doch beantwortet, oder? Warum eine "Liste", wenn ich nur **ein** Element habe?

stimmt, da haste eigentlich auch wieder wahr. ;) andererseits... (*brille zurechtrücken...*) wandeln wir dieses eine element dann direkt wieder in eine liste um, damit es zu unserem vorhandenen arguments parsing passt und mit diesem verwendet werden kann. das fühlt sich doppelt an (dry).

2024-02-01 11:25 UTC, cagix commented
> > (2) "ohnehin eine Liste mit nur einem Elem": naja, dann ist Deine Frage doch beantwortet, oder? Warum eine "Liste", wenn ich nur **ein** Element habe?
> 
> 
> 
> stimmt, da haste eigentlich auch wieder wahr. ;) andererseits... (*brille zurechtrücken...*) wandeln wir dieses eine element dann direkt wieder in eine liste um, damit es zu unserem vorhandenen arguments parsing passt und mit diesem verwendet werden kann. das fühlt sich doppelt an (dry).

mag sein. aber eine funktion, die immer genau ein element berechnet, sollte keine liste zurück geben. wenn man an einer anderen stelle dann eine liste übergeben muss und das auch eine ein-elementige liste sein kann, dann ist das ne andere sache.

2024-02-01 11:33 UTC, tgrothe commented
> wenn man an einer anderen stelle dann eine liste übergeben muss und das ***auch*** eine ein-elementige liste sein kann, dann ist das ne andere sache.

das stimmt, die jar kann ja auch mit ***mehreren*** args aufgerufen werden. nicht dran gedacht.

2024-02-01 12:38 UTC, cagix commented
> Erde an @cagix , hat das funktioniert? 😉 Ich frage nur, weil ich ja keinen Mac hab.

@tgrothe kein grund zu drängeln.

`./gradlew start`: nix. gar nix. nach der Ausgabe des Betriebssystem bleibt es stehen, es erscheint kein Fenster.

`java -jar build/libs/Starter.jar`: FileChooser poppt hoch, danach dann der Dungeon (sofern ich eine .dng auswähle). Wenn ich nix auswähle, stirbt das Ding mit einem Stacktrace "No DNG file selected!". Ich dachte, wir hatten darüber gesprochen, dass es hier keine Exception gibt und sich das Programm mit einer Fehlermeldung beendet?

`java -jar build/libs/Starter.jar --args ./dungeon/test_resources/config1.dng`: startet direkt in den Dungeon.

2024-02-01 12:42 UTC, cagix commented
> > Erde an @cagix , hat das funktioniert? 😉 Ich frage nur, weil ich ja keinen Mac hab.
> 
> @tgrothe kein grund zu drängeln.
> 
> `./gradlew start`: nix. gar nix. nach der Ausgabe des Betriebssystem bleibt es stehen, es erscheint kein Fenster.
> 
> `java -jar build/libs/Starter.jar`: FileChooser poppt hoch, danach dann der Dungeon (sofern ich eine .dng auswähle). Wenn ich nix auswähle, stirbt das Ding mit einem Stacktrace "No DNG file selected!". Ich dachte, wir hatten darüber gesprochen, dass es hier keine Exception gibt und sich das Programm mit einer Fehlermeldung beendet?
> 
> `java -jar build/libs/Starter.jar --args ./dungeon/test_resources/config1.dng`: startet direkt in den Dungeon.

@tgrothe Wenn ich in `build.gradle` den die Erkennung des OS und das zusätzlich Flag für macOS rausnehme, geht es auch mit `./gradlew start`. Und der alte Kram (`gradlew run`) geht auch noch.

2024-02-01 12:44 UTC, cagix commented
@tgrothe D.h. der Weg geht. Bitte für das Entfernen von 

```
    if (System.properties['os.name'].toLowerCase().contains('mac')) {
        jvmArgs('-XstartOnFirstThread')
    }
```

und das Einbauen von `com.badlogicgames.gdx:gdx-lwjgl3-glfw-awt-macos` einen extra PR aufmachen. Dort beschreiben, was passiert und warum und auch den Link unterbringen (https://libgdx.com/news/2022/05/gdx-1-11). 

Danach dann in diesem PR (rebasen nach Merge) nur noch den FileChooser dazu.

2024-02-01 12:57 UTC, tgrothe commented
> > Erde an @cagix , hat das funktioniert? 😉 Ich frage nur, weil ich ja keinen Mac hab.
> 
> @tgrothe kein grund zu drängeln.
> 
> `./gradlew start`: nix. gar nix. nach der Ausgabe des Betriebssystem bleibt es stehen, es erscheint kein Fenster.
> 
> `java -jar build/libs/Starter.jar`: FileChooser poppt hoch, danach dann der Dungeon (sofern ich eine .dng auswähle). Wenn ich nix auswähle, stirbt das Ding mit einem Stacktrace "No DNG file selected!". Ich dachte, wir hatten darüber gesprochen, dass es hier keine Exception gibt und sich das Programm mit einer Fehlermeldung beendet?
> 
> `java -jar build/libs/Starter.jar --args ./dungeon/test_resources/config1.dng`: startet direkt in den Dungeon.
> 

Das ist super 😊

(1) das liegt dann an first thread...

(2) so soll es sein. das Spiel sollte im else Fall nicht starten.

(3) so soll es sein.

((4)) ich mache für die dependency einen neuen pr + issue auf. :) dann kann start on first thread ja weg. wieder eine "größere" Änderung... dauert aber noch etwas, bin zurzeit nicht an meinem Schreibtisch.

2024-02-01 13:03 UTC, cagix commented
> (2) so soll es sein. das Spiel sollte im else Fall nicht starten.

Ja, es sollte nicht starten. Aber es sollte **nicht** mit einem Stracktrace sterben! 

Hintergrund: Das sollen ja auch Nicht-Informatiker nutzen. D.h. es reicht eine Fehlermeldung, ein Stracktrace für die Zielgruppe einfach zu fett.

2024-02-01 13:53 UTC, tgrothe commented
> > (2) so soll es sein. das Spiel sollte im else Fall nicht starten.
> 
> Ja, es sollte nicht starten. Aber es sollte **nicht** mit einem Stracktrace sterben!
> 
> Hintergrund: Das sollen ja auch Nicht-Informatiker nutzen. D.h. es reicht eine Fehlermeldung, ein Stracktrace für die Zielgruppe einfach zu fett.

Danke noch mal für die Erklärung. Dann baue ich an der Stelle ein exit 0 ein.

2024-02-01 15:51 UTC, cagix commented
@tgrothe bitte ein rebase und dann ein review

2024-02-01 17:38 UTC, cagix requested changes
@tgrothe Ein paar Vorschläge. Ich würde insbesondere das Hantieren mit den exotischen Threading-Klassen eher vermeiden - brauchen wir wirklich eine CountDownLatch? 
(Dito die AtomicReference, obwohl die direkt von IJ vorgeschlagen wird, wenn man sie nicht nutzt. Dennoch halte ich das in unserem Szenario für Overkill. Aber lass es drin - die "Fehlermeldung" von IJ nervt auch.)

2024-02-01 17:38 UTC, cagix commented on dungeon/src/starter/Starter.java
> +    SwingUtilities.invokeLater(
@tgrothe Wenn Du hier [`SwingUtilities.invokeAndWait`](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/SwingUtilities.html#invokeAndWait(java.lang.Runnable)) nimmst, kannst Du Dir das umständliche Hantieren mit CountDownLatch sparen. Was denkst Du?

2024-02-01 17:38 UTC, cagix commented on dungeon/src/starter/Starter.java
> +          fileChooser.setFileFilter(new FileNameExtensionFilter("Only DNG files", "dng"));
```suggestion
          fileChooser.setFileFilter(new FileNameExtensionFilter(".dng file", "dng"));
```

2024-02-01 17:38 UTC, cagix commented on dungeon/src/starter/Starter.java
> +              selectSingleDngFile().orElseThrow(() -> new IOException("No DNG file selected!")));
Das ist blöd - wenn nix ausgewählt, dann Stacktrace. Hier sollte eine einfache Ausgabe auf stderr gemacht werden und das Programm normal beendet werden.

2024-02-01 17:38 UTC, cagix commented on dungeon/src/starter/Starter.java
> +      throw new RuntimeException(e);
Das ist blöd - wenn nix ausgewählt, dann Stacktrace. Hier sollte eine einfache Ausgabe auf stderr gemacht werden und das Programm normal beendet werden.

2024-02-01 17:38 UTC, cagix commented on dungeon/src/starter/Starter.java
> +    AtomicReference<Optional<String>> path = new AtomicReference<>();
```suggestion
    AtomicReference<Optional<String>> path = new AtomicReference<>(Optional.empty());
```

2024-02-01 17:38 UTC, cagix commented on dungeon/src/starter/Starter.java
> +          }
```suggestion
          }
```

2024-02-01 17:45 UTC, cagix commented
@tgrothe irgendwie ist der ausstieg im fehlerfall (keine konfiguration ausgewählt/angegeben) noch irgendwie holperig und nicht gut. 

nur mal ins unreine gesprochen: was hältst du davon, die methode `processCLIArguments` wieder auf die alte struktur (mit der geänderten listen-signatur) zu setzen und im `main()` zuerst deine neue hilfsmethode mit `Arrays.asList(args)` aufzurufen? diese müsste dann prüfen, ob die liste leer ist - wenn nicht, würde das einfach das ergebnis der methode sein, ansonsten wird der filechooser aufgemacht. wenn da was zurückkommt, wird das als liste zurückgeliefert. sonst eine exception. dann kann im `main()` um den aufruf der hilfsmethode ein try/catch gebastelt werden und hier im fehlerfall der "sanfte" ausstieg erfolgen. entsprechend kein try/catch in der hilfsmethode.

2024-02-01 19:40 UTC, tgrothe commented on dungeon/src/starter/Starter.java
> +    SwingUtilities.invokeLater(
Gute Idee, weniger Zeilen, weniger Geraffel, verständlicher und semantisch nicht anders ... dann aber leider noch um eine zusätzliche Exception kümmern (das ist aber nicht schlimm). Ich baue das ein.

2024-02-01 19:41 UTC, tgrothe commented on dungeon/src/starter/Starter.java
> +              selectSingleDngFile().orElseThrow(() -> new IOException("No DNG file selected!")));
java stderr oder logger? ;)

2024-02-01 19:52 UTC, cagix commented on dungeon/src/starter/Starter.java
> +    SwingUtilities.invokeLater(
die exception hattest du doch auch jetzt schon, nur tiefer beim "await"?

2024-02-01 19:54 UTC, cagix commented on dungeon/src/starter/Starter.java
> +              selectSingleDngFile().orElseThrow(() -> new IOException("No DNG file selected!")));
weiss nicht. logger reicht im prinzip, aber den kann man abschalten. und das wäre ja schon was wichtiges für die kunden? ist mir aber eher egal.

2024-02-01 20:09 UTC, tgrothe commented
> @tgrothe irgendwie ist der ausstieg im fehlerfall (keine konfiguration ausgewählt/angegeben) noch irgendwie holperig und nicht gut.
> 
> nur mal ins unreine gesprochen: was hältst du davon, die methode `processCLIArguments` wieder auf die alte struktur (mit der geänderten listen-signatur) zu setzen und im `main()` zuerst deine neue hilfsmethode mit `Arrays.asList(args)` aufzurufen? diese müsste dann prüfen, ob die liste leer ist - wenn nicht, würde das einfach das ergebnis der methode sein, ansonsten wird der filechooser aufgemacht. wenn da was zurückkommt, wird das als liste zurückgeliefert. sonst eine exception. dann kann im `main()` um den aufruf der hilfsmethode ein try/catch gebastelt werden und hier im fehlerfall der "sanfte" ausstieg erfolgen. entsprechend kein try/catch in der hilfsmethode.
> 
> edit: im inneren der hilfsmethode brauchen wir dann auch kein `Optional` mehr.

hmmm, danke für dein review. die idee gefällt mir ...

wir haben anfangs ja nur eine lineare methodenaufrufsfolge. d. h., der ausgang oder das ergebnis jeder methode wird nur genau einmal weiterverwendet. dann wäre es fast egal, welcher rückgabetyp gewählt wird. wir sollten aber so wenig wrapper-typen wie möglich einsetzen, imho.

vielleicht wäre es auch sinnvoll, die eine swing-methode in eine hilfsklasse in ein extra package zu verlagern? nur der übersicht wegen und falls da später noch weitere swing/awt sachen hinzukommen könnten (oder ist das yagni?). was hälst du davon?

um das oder um die try/catch(es) müssen wir uns auch kümmern, weil das spiel dann ja "graceful" beendet werden soll, bzw. nicht mit einem stacktrace nicht starten soll. am besten ziemlich weit oben in der methodenaufrufsfolge, aber auch nicht direkt in der main method?

2024-02-01 20:19 UTC, tgrothe commented on dungeon/src/starter/Starter.java
> +    SwingUtilities.invokeLater(
ja genau, bei `CountDownLatch`

2024-02-01 20:37 UTC, cagix commented
> > @tgrothe irgendwie ist der ausstieg im fehlerfall (keine konfiguration ausgewählt/angegeben) noch irgendwie holperig und nicht gut.
> 
> > 
> 
> > nur mal ins unreine gesprochen: was hältst du davon, die methode `processCLIArguments` wieder auf die alte struktur (mit der geänderten listen-signatur) zu setzen und im `main()` zuerst deine neue hilfsmethode mit `Arrays.asList(args)` aufzurufen? diese müsste dann prüfen, ob die liste leer ist - wenn nicht, würde das einfach das ergebnis der methode sein, ansonsten wird der filechooser aufgemacht. wenn da was zurückkommt, wird das als liste zurückgeliefert. sonst eine exception. dann kann im `main()` um den aufruf der hilfsmethode ein try/catch gebastelt werden und hier im fehlerfall der "sanfte" ausstieg erfolgen. entsprechend kein try/catch in der hilfsmethode.
> 
> > 
> 
> > edit: im inneren der hilfsmethode brauchen wir dann auch kein `Optional` mehr.
> 
> 
> 
> hmmm, danke für dein review. die idee gefällt mir ...
> 
> 
> 
> wir haben anfangs ja nur eine lineare methodenaufrufsfolge. d. h., der ausgang oder das ergebnis jeder methode wird nur genau einmal weiterverwendet. dann wäre es fast egal, welcher rückgabetyp gewählt wird. wir sollten aber so wenig wrapper-typen wie möglich einsetzen, imho.

ich finde die arrays irgendwie nicht schön, aber du hast recht. wenn wir es bei string[]  belassen, sparen wir konvertierungen. und für den einen string vom filechooser kann man auch ein neues array drumrum bauen und zurückschicken.


> 
> 
> 
> vielleicht wäre es auch sinnvoll, die eine swing-methode in eine hilfsklasse in ein extra package zu verlagern? nur der übersicht wegen und falls da später noch weitere swing/awt sachen hinzukommen könnten (oder ist das yagni?). was hälst du davon?

nee, nicht hilfsklasse. wenn es wirklich nochmal gebraucht werden sollte, kann man es dann immer noch refactoren ... 

und ne extra hilfsklasse macht es in diesem fall nicht wirklich lesbarer/ übersichtlicher.

yagni.

> 
> 
> 
> um das oder um die try/catch(es) müssen wir uns auch kümmern, weil das spiel dann ja "graceful" beendet werden soll, bzw. nicht mit einem stacktrace nicht starten soll. am besten ziemlich weit oben in der methodenaufrufsfolge, aber auch nicht direkt in der main method?

try/catch nur im main um die hilfsmethode drumrum - eine stelle zum ausstieg, wenn keine config angegeben/ausgewählt wurde. und man sieht es dann auch sofort ...

im grunde sollte man das auch nochmal um die methode von @malt-r machen, es kann ja sein, dass beim verarbeiten der config was schief geht und man deshalb aussteigt. das ist aber  teil für ein refactoring später.

2024-02-02 09:28 UTC, cagix commented on dungeon/src/starter/Starter.java
> +      throw new RuntimeException(e);
nvm, das fällt ja eh raus, wenn https://github.com/Dungeon-CampusMinden/Dungeon/pull/1365#issuecomment-1921874461 umgesetzt ist.

2024-02-02 11:24 UTC, tgrothe commented
> @tgrothe irgendwie ist der ausstieg im fehlerfall (keine konfiguration ausgewählt/angegeben) noch irgendwie holperig und nicht gut.
> 
> nur mal ins unreine gesprochen: was hältst du davon, die methode `processCLIArguments` wieder auf die alte struktur (mit der geänderten listen-signatur) zu setzen und im `main()` zuerst deine neue hilfsmethode mit `Arrays.asList(args)` aufzurufen? diese müsste dann prüfen, ob die liste leer ist - wenn nicht, würde das einfach das ergebnis der methode sein, ansonsten wird der filechooser aufgemacht. wenn da was zurückkommt, wird das als liste zurückgeliefert. sonst eine exception. dann kann im `main()` um den aufruf der hilfsmethode ein try/catch gebastelt werden und hier im fehlerfall der "sanfte" ausstieg erfolgen. entsprechend kein try/catch in der hilfsmethode.
> 
> edit: im inneren der hilfsmethode brauchen wir dann auch kein `Optional` mehr.

das hab ich jetzt so umgesetzt. bitte noch mal schauen.

2024-02-02 15:12 UTC, cagix requested changes
@tgrothe ich habe ne weile nachgedacht. 

die struktur, wo ein try/catch nur um den aufruf vom selectsingledngfile() drum ist, finde ich nicht so gut: es ist viel optischer clutter und lenkt von der eigentlichen aktion und auch dem gesamt-flow im main() ab.

die alternative, das try/catch nochmal als eigene funktion auszulagern, fand ich auch nicht so schön: dann ist der ausstieg doch wieder in einer hilfsfunktion und man sieht im main() nicht, was passiert.

da bei den operationen von @malt-r eine ioexception geworfen werden kann, würde ich alles im main() in ein großes try/catch packen und am ende nach den fällen differenzieren: keine datei angegeben/selektiert und probleme beim einlesen der datei. so ist die hauptfunktion gut erkennbar, und am ende vom main() hat man die fehlerbehandlung. dabei spart man sogar das "system.exit", weil man hier sowieso am ende ist. 

ich möchte diesen code als main-funktion haben (kann das leider nicht als vorschlag zum draufklicken einstellen):

```java
  public static void main(String[] args) {
    try {
      // if file names have been supplied on CLI, let's use these
      // otherwise try to get a file name of a configuration file interactively
      String[] dslFileNames = args.length > 0 ? args : new String[] {selectSingleDngFile()};

      // read in DSL-Files
      Set<DSLEntryPoint> entryPoints = processCLIArguments(dslFileNames);

      // some game Setup
      configGame();
      // will load the level to select the task/DSL-Entrypoint on Game start
      taskSelectorOnSetup(entryPoints);

      // will generate the TaskDependencyGraph, execute the TaskBuilder, generate and set the
      // Level and generate the PetriNet after the player selected an DSLEntryPoint
      onEntryPointSelection();
      startTime = System.currentTimeMillis();

      // let's do this
      Game.run();

    } catch (NullPointerException | InterruptedException | InvocationTargetException e) {
      // no configuration, so let's abort here
      System.err.println("No .dng file selected. Exiting ...");
    } catch (IOException e) {
      // could not read configuration, so let's abort here
      System.err.println("Couldn't read specified .dng. Exiting ...");
    }
  }
```

was denkst du?

btw: das object.requirenonnull brauchst du nicht - versuch mal ein neues array mit null als "element" anzulegen :)

2024-02-02 15:12 UTC, cagix commented on dungeon/src/starter/Starter.java
> +  /**
```suggestion
  /*
```

2024-02-02 15:50 UTC, tgrothe commented
> was denkst du?

Dein Vorschlag gefällt mir sehr gut. So entspricht es auch eher der Leserichtung... (wenn man nicht gerade in China ist 😉).

Problematisch sehe ich eigentlich nur, wenn es noch andere Methodenaufrufe geben könnte, die auch eine IOException auslösen könnten (wegen der Unterscheidung was/wo)... Aber vermutlich ist das yagni.

Und die Reihenfolge (du hattest `NullPointerException | InterruptedException | InvocationTargetException e` gewählt) würde ich alphabetisch machen - oder was zuerst ausgelöst werden könnte.

> btw: das object.requirenonnull brauchst du nicht - versuch mal ein neues array mit null als "element" anzulegen :)

danke, nicht gewusst... aber ich hätte es ahnen können, weil IJ an der Stelle das nicht vorgeschlagen hatte 😀

2024-02-02 15:59 UTC, cagix commented
> Problematisch sehe ich eigentlich nur, wenn es noch andere Methodenaufrufe geben könnte, die auch eine IOException auslösen könnten (wegen der Unterscheidung was/wo)... Aber vermutlich ist das yagni.

ja, schon. ich vermute aber, dass das wirklich aus der `processCLIArguments` kommt - alles andere macht ja kein io mehr. ... obwohl, es könnte freilich noch probleme mit den sprites geben, aber das wird iirc intern abgefangen.

das dumme ist nur, wenn man wirklich um jede der "kritischen" statements ein eigenes try/catch macht (was an sich sinnvoll ist), kann man vor lauter wald nix mehr erkennen.

> 
> Und die Reihenfolge (du hattest `NullPointerException | InterruptedException | InvocationTargetException e` gewählt) würde ich alphabetisch machen - oder was zuerst ausgelöst werden könnte.

ja, mach. das kann auf der ebene sowieso niemand wirklich nachvollziehen, wo jetzt was warum herkommt.

2024-02-02 16:27 UTC, tgrothe commented
dann können wir das ding schließen, bevor es eier legt 😉 

edit: ich bin mir immer unsicher, wann ich was auf draft oder ready for review setzen sollte 😕

2024-02-02 18:27 UTC, cagix approved these changes
lgtm 👍

2024-02-02 18:28 UTC, merged

2024-02-02 18:28 UTC, cagix commented
thx 🍾