add file practice_dungeon concept
Dungeon-CampusMinden/Dungeon pull request #1439
Opened 2024-03-01 14:42 UTC by Denniso3

Wir haben uns für den Namen: "practice-dungeon" entschieden

2024-03-01 14:57 UTC, cagix commented
> Wir haben uns für den Namen: "practice-dungeon" entschieden

echt? "prog2-dungeon" gab es nicht?

2024-03-01 14:58 UTC, cagix commented
@Denniso3 Oder sowas wie "Mini-Dungeon"?

2024-03-01 15:02 UTC, tgrothe commented
Hatten an tasks-dungeon, exercise-dungeon, dungeon-force und Prog-2 gedacht, aber practice-dungeon war dann iwie naheliegender

2024-03-01 15:06 UTC, cagix requested changes
@Denniso3 Danke. 

Ich hätte irgendwie erwartet, dass es einen neuen Ordner für das neue Spiel gibt (parallel zu `game/` und `dungeon/`). Darin dann ein `doc/`-Ordner und da drin Dein Markdown-File plus ein `img/`-Ordner mit den Abbildungen. 

(In einem nächsten Schritt müsste der neue Ordner dann zu einem Gradle-Subprojekt gemacht und eingebunden werden.)

Zusätzlich bitte mal in die restliche Doku schauen: Wir verwenden hier statt 

```markdown
# H1 Title
```

einen YAML-Header, danach geht es dann mit H2-Header als höchste Gliederungsstufe weiter:

```markdown
---
title: "wuppie fluppie - mein toller titel"
---
```

Die Abbildungen bitte auch mit Markdown-Links einbinden:

```markdown
![Das ist die Caption/Bildbeschreibung](img/bildname.png)
```

Dabei passt natürlich die Skalierung nicht, aber das erleichtert eine Weiterverarbeitung ungemein :)

2024-03-01 15:06 UTC, cagix commented
> Hatten an tasks-dungeon, exercise-dungeon, dungeon-force und Prog-2 gedacht, aber practice-dungeon war dann iwie naheliegender

@tgrothe @Denniso3 @JudiTeller Hmmm. Wie wäre es mit "Dungeon-Dojo"? :)

2024-03-01 15:16 UTC, Denniso3 commented
Dojo-Dungeon hört sich auch gut an

2024-03-01 15:31 UTC, tgrothe commented
> > Hatten an tasks-dungeon, exercise-dungeon, dungeon-force und Prog-2 gedacht, aber practice-dungeon war dann iwie naheliegender
> 
> @tgrothe @Denniso3 @JudiTeller Hmmm. Wie wäre es mit "Dungeon-Dojo"? :)
> 
> Edit: oder umgedreht: "Dojo-Dungeon"?

Dann lieber "richtigherum": Dungeon-Dojo

2024-03-01 15:39 UTC, cagix commented
Ja prima, dann haben wir doch nen Namen. "Dojo-Dungeon" it is.

2024-03-02 16:41 UTC, tgrothe commented
> Ja prima, dann haben wir doch nen Namen. "Dojo-Dungeon" it is.

Ich bin mit der Umbenennung einverstanden. Für die anderen beiden kann ich aber nicht sprechen.

2024-03-02 16:50 UTC, cagix commented
@tgrothe @Denniso3 @JudiTeller 

ich würde sagen, ich habe das grad entschieden. kein weiteres einverständnis oder diskussion nötig. bitte fokussiert euch auf die inhalte.

2024-03-02 18:07 UTC, tgrothe commented
@cagix ok, machen wir... hier geht es morgen nachmittag weiter. ;)

2024-03-02 18:52 UTC, cagix commented
> @cagix ok, machen wir... hier geht es morgen nachmittag weiter. ;)

@tgrothe dein arbeitseifer in allen ehren!

da dieses issue aber im rahmen deiner aufgabe als shk liegt und die tätigkeiten entsprechend als vertragliche tätigkeit/arbeitszeit betrachtet werden muss, muss ich dich dringend auf die einhaltung der arbeitszeitgesetze und der vereinbarten wöchentlichen arbeitszeit hinweisen!

2024-03-04 10:34 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +## 3 Level 2: ”Tempel der verlorenen Geheimnisse”
```suggestion
## Level 2: ”Tempel der verlorenen Geheimnisse”
```

2024-03-04 10:35 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +</div>
```suggestion
![](img/concept_level_structure.png)
```

2024-03-04 10:35 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +## 4 Level 3: ”Kerker des Grauens”
```suggestion
## Level 3: ”Kerker des Grauens”
```

2024-03-04 10:35 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +</div>
```suggestion
![](img/concept_level_structure.png)
```

2024-03-04 10:35 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +## 5 Level 4: ”Die Vulkanhöhle”
```suggestion
## Level 4: ”Die Vulkanhöhle”
```

2024-03-04 10:35 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +</div>
```suggestion
![](img/concept_level_structure.png)
```

2024-03-04 10:36 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +## 6 Level 5: ”Spezial-Welt Bielefeld”
```suggestion
## Level 5: ”Spezial-Welt Bielefeld”
```

2024-03-04 10:36 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +## 7 Ziele
```suggestion
## Ziele
```

2024-03-04 10:36 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +      worten, um den Boss zu besiegen.
```suggestion
    - Der Spieler muss die Fragen richtig beantworten, um den Boss zu besiegen.
```

2024-03-04 10:39 UTC, cagix commented on dungeon/doc/practice_dungeon.md
> +      worten, um den Boss zu besiegen.
Die Trennung machen hinterher irgendwelche Tools, das ist nix, was wir einchecken.

2024-03-04 10:43 UTC, cagix reviewed
@Denniso3 Hier passieren zwei verschiedene Dinge auf einmal: Du fügst eine neue Ordnerstruktur zum Gradle-Projekt hinzu **und** Du fügst eine initiale Doku hinzu. Das finde ich nicht so gut.

mein vorschlag wäre, in einem pr das konzept (dokumentation) hinzuzufügen, und in einem zweiten pr die gradle-strukturen anzupassen. dabei sollte es dann aber auch die ordnerstruktur plus die referenzierten klassen geben (kann ja erstmal leer (Order: ".gitkeep", Klasse: leeres Main - NOOP) sein).

2024-03-04 10:43 UTC, cagix commented on dojo-dungeon/build.gradle
> +    id 'antlr'
```suggestion
```

2024-03-04 10:43 UTC, cagix commented on dojo-dungeon/build.gradle
> +    antlr supportDependencies.antlr
```suggestion
```

2024-03-04 10:43 UTC, cagix commented on dojo-dungeon/build.gradle
> +sourceSets.main.java.srcDirs = ['src/', "$projectDir/build/generated-src/antlr/main/"]
```suggestion
sourceSets.main.java.srcDirs = ['src/']
```

2024-03-04 10:43 UTC, cagix commented on dojo-dungeon/build.gradle
> +}
```suggestion
```

2024-03-04 10:43 UTC, cagix commented on dojo-dungeon/build.gradle
> +
```suggestion
```

2024-03-04 10:43 UTC, cagix commented on dojo-dungeon/build.gradle
> +    mainClass = 'starter.DojoStarter'
das ist blöd. wenn wir diesen pr mergen wollen, sollte es auch diese klasse geben.

2024-03-04 10:44 UTC, cagix commented on dojo-dungeon/doc/dojo_dungeon_concept.md
> +Titel ”Dojo-Dungeon”. In diesem Spiel erkundet der Spieler verschiedene Level,
```suggestion
Titel "Dojo-Dungeon". In diesem Spiel erkundet der Spieler verschiedene Level,
```

2024-03-04 10:45 UTC, cagix commented on dojo-dungeon/doc/dojo_dungeon_concept.md
> +      terholz und moosbedecktem Boden.
```suggestion
    - Ein geheimnisvoller Wald mit dichtem 
      Unterholz und moosbedecktem Boden.
```

2024-03-04 10:45 UTC, cagix commented on dojo-dungeon/doc/dojo_dungeon_concept.md
> +
```suggestion
```

2024-03-04 12:02 UTC, Denniso3 commented
Dann kann man eigentlich hier zumachen.

2024-03-04 14:17 UTC, cagix commented
> Dann kann man eigentlich hier zumachen.

Naja, eigentlich hättest Du hier nur das Gradle-Zeugs in einen eigenen Branch auszweigen müssen?

2024-03-04 14:50 UTC, closed without merging