Rename deamon -> daemon
Dungeon-CampusMinden/Dungeon pull request #1485
Opened 2024-04-08 18:27 UTC by tgrothe

Dieser Pull-Request benennt "deamon" in "daemon" um.

Vorher:

```
$ grep -r -C 1 "deamon" blockly/ dojo-dungeon/ dungeon/ game/ doc/
dungeon/src/contrib/entities/MonsterFactory.java-    new SimpleIPath("character/monster/imp"),
dungeon/src/contrib/entities/MonsterFactory.java:    new SimpleIPath("character/monster/big_deamon"),
dungeon/src/contrib/entities/MonsterFactory.java-    new SimpleIPath("character/monster/big_zombie"),

$ find . -name "*deamon*"
./dungeon/assets/character/monster/big_deamon
```

closes #1483

2024-04-09 05:11 UTC, cagix commented
@tgrothe Danke für den Beitrag. Drei Beobachtungen:

1. Im ersten Kommentar des PR bitte **immer** der Dreiklang: 
    - Was ist kaputt? (Was habe ich beobachtet, was habe ich erwartet?)
    - Was ist der Fix? (Was ist der Lösungsansatz?)
    - Gibt es mögliche API- oder Verhaltensänderungen, bricht für irgendwen irgendwas?
2. Warum fährst Du für eine simple Umbenennung die ganz großen Geschütze auf und forderst ein Review von gleich mehreren Leuten, zumal @AMatutat im Moment gar nicht aktiv im Projekt arbeitet? Das führt nur dazu, dass er Dich/uns auf "ignore" setzt und dann in wirklich wichtigen Fällen nicht mehr reagiert, weil er es nicht mehr mitkriegt :/
3. Was ist der Sinn hinter den "komplizierten" Optionen? Reicht nicht ein simples `grep -r "deamon"`? Mit dem `-C 1` clutterst Du die Ausgabe mit lauter hier nicht relevanten Angaben?

2024-04-09 05:13 UTC, cagix commented
@tgrothe Ich stelle diesen PR noch einmal zurück. Wir haben zwei abhängige Projekte (Forks), die in den nächsten Wochen gemergt werden sollen. Bei euch im Dojo könntet ihr die Änderung mit rüberziehen, dann wäre der Merge kein Thema. Beim Dev wird nicht mehr aktiv entwickelt afaik, das gibt dann nach dem Merge Probleme, weil dann die Textur fehlt und man sich erst an diese Umbenennung hier erinnern muss.

2024-04-09 05:29 UTC, cagix requested changes
@tgrothe Mir ist aufgefallen, dass es noch einen weiteren Typo bei den Dämonen gibt :) ... Die Texturen selbst werden nur "demon" statt "daemon" geschrieben: `dungeon/assets/character/monster/big_daemon/idle/big_demon_idle_anim_f0.png` ... Das sollte mit angepasst werden.

Hintergrund: Demon und Daemon haben eine unterschiedliche Bedeutung - ein Demon ist eine negative Entität, während ein Daemon eine hilfreiche Entität mit supernatürlichen Kräften ist. Wir wollen die letztere Bedeutung, auch in Anlehnung an die Unix-Daemons :)

2024-04-09 07:02 UTC, tgrothe commented
Moin und Danke erst mal. ☕ 

> 2. Warum fährst Du für eine simple Umbenennung die ganz großen Geschütze auf und forderst ein Review von gleich mehreren Leuten, zumal @AMatutat im Moment gar nicht aktiv im Projekt arbeitet? Das führt nur dazu, dass er Dich/uns auf "ignore" setzt und dann in wirklich wichtigen Fällen nicht mehr reagiert, weil er es nicht mehr mitkriegt :/

War ein versehen, bzw. wurde als erstes von GitHub vorgeschlagen. Nun weiß ich Bescheid.


> 3. Was ist der Sinn hinter den "komplizierten" Optionen? Reicht nicht ein simples `grep -r "deamon"`? Mit dem `-C 1` clutterst Du die Ausgabe mit lauter hier nicht relevanten Angaben?

Wenn es in den Docs dazu etwas gegeben hätte, wäre `-C 1` wegen des Kontexts sinnvoll gewesen ... das gab es aber nicht. Mea culpa.

---

> @tgrothe Mir ist aufgefallen, dass es noch einen weiteren Typo bei den Dämonen gibt :) ... Die Texturen selbst werden nur "demon" statt "daemon" geschrieben: `dungeon/assets/character/monster/big_daemon/idle/big_demon_idle_anim_f0.png` ... Das sollte mit angepasst werden.
> 
> Hintergrund: Demon und Daemon haben eine unterschiedliche Bedeutung - ein Demon ist eine negative Entität, während ein Daemon eine hilfreiche Entität mit supernatürlichen Kräften ist. Wir wollen die letztere Bedeutung, auch in Anlehnung an die Unix-Daemons :)

Danke für das Recherchieren. :) Ich nahm an, demon wäre nur eine andere Schreibweise für daemon, und deamon wäre in jeden Fall falsch ...

Aber dann weiß ich nun Bescheid und kann "später" den "demon" (bzw. die demons ...) auch noch umbenennen.

2024-04-25 03:45 UTC, tgrothe commented
Sieht gut aus:

```
$ grep -r "deamon" --exclude-dir=.git --exclude-dir=.gradle --exclude-dir=.idea || grep -r "demon" --exclude-dir=.git --exclude-dir=.gradle --exclude-dir=.idea || find . -name '*deamon*' -not -path './.git/*' -exec bash -c 'echo mv $0 ${0/deamon/daemon}' {} \; || find . -name '*demon*' -not -path './.git/*' -exec bash -c 'echo mv $0 ${0/demon/daemon}' {} \;

dungeon/src/contrib/components/ItemComponent.java: * <p>The {@link contrib.entities.WorldItemBuilder WorldItemBuilder} demonstrates how to create an

```

"demonstrates" können wir ignorieren

2024-04-25 06:53 UTC, cagix approved these changes
sieht gut aus, danke - ich stelle das trotzdem nochmal zurück, https://github.com/Dungeon-CampusMinden/Dungeon/pull/1485#issuecomment-2044161914 gilt immer noch :)

2024-04-25 09:02 UTC, tgrothe commented
> sieht gut aus, danke - ich stelle das trotzdem nochmal zurück, [#1485 (comment)](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1485#issuecomment-2044161914) gilt immer noch :)

jup, danke ... heute morgen hatte ich auch noch nicht genug kaffee gehabt. ;)

2024-06-24 12:40 UTC, tgrothe commented
@cagix ist das hier noch aktuell? ich sehe keine merge-konflikte und denke, es sollte fertig sein.

2024-06-24 14:53 UTC, cagix commented
> sieht gut aus, danke - ich stelle das trotzdem nochmal zurück, [#1485 (comment)](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1485#issuecomment-2044161914) gilt immer noch :)

danke für das herumgepinge, aber [#1485 (comment)](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1485#issuecomment-2044161914) gilt immer noch ...

2024-06-24 15:53 UTC, tgrothe commented
> > sieht gut aus, danke - ich stelle das trotzdem nochmal zurück, [#1485 (comment)](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1485#issuecomment-2044161914) gilt immer noch :)
> 
> danke für das herumgepinge, aber [#1485 (comment)](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1485#issuecomment-2044161914) gilt immer noch ...

ja, ok, es sollte nur nicht in vergessenheit geraten ... ich setze mich jetzt auf meine hände :D

2024-07-11 16:14 UTC, cagix commented
@Flamtky Sag mal, wenn wir den hier mergen - stört das Deine Kreise? Du müsstest bei Dir dann auch mal "deamon" in "daemon" umbenennen, falls Du das irgendwo in Deinem Code referenzierst ... Alternativ warte ich hier einfach, bis der DevDungeon vollständig gemergt ist.

2024-07-11 17:08 UTC, Flamtky commented
> @Flamtky Sag mal, wenn wir den hier mergen - stört das Deine Kreise? Du müsstest bei Dir dann auch mal "deamon" in "daemon" umbenennen, falls Du das irgendwo in Deinem Code referenzierst ... Alternativ warte ich hier einfach, bis der DevDungeon vollständig gemergt ist.

Kann gemergt werden, ich verwende nur einmal das wort `deamon`.

2024-07-11 17:47 UTC, cagix approved these changes
ok, dann endlich zu damit.

2024-07-11 17:47 UTC, merged

2024-07-11 17:48 UTC, cagix commented
> > @Flamtky Sag mal, wenn wir den hier mergen - stört das Deine Kreise? Du müsstest bei Dir dann auch mal "deamon" in "daemon" umbenennen, falls Du das irgendwo in Deinem Code referenzierst ... Alternativ warte ich hier einfach, bis der DevDungeon vollständig gemergt ist.
> 
> Kann gemergt werden, ich verwende nur einmal das Wort `deamon`.

@Flamtky dann bitte nicht vergessen, das auch bei dir umzubenennen :)

2024-07-11 19:39 UTC, Flamtky commented
> > > @Flamtky Sag mal, wenn wir den hier mergen - stört das Deine Kreise? Du müsstest bei Dir dann auch mal "deamon" in "daemon" umbenennen, falls Du das irgendwo in Deinem Code referenzierst ... Alternativ warte ich hier einfach, bis der DevDungeon vollständig gemergt ist.
> > 
> > Kann gemergt werden, ich verwende nur einmal das Wort `deamon`.
> 
> @Flamtky dann bitte nicht vergessen, das auch bei dir umzubenennen :) 
> 
> Im Dev-Dungeon ist afaik die Klasse `devDungeon/src/entities/MonsterType.java:      "character/monster/big_deamon"` betroffen.

Lokal schon passiert 😅