Tooling: Fix junit and mockito dependencies
Dungeon-CampusMinden/Dungeon pull request #1491
Opened 2024-04-15 11:24 UTC by tgrothe

Hierdurch werden die Testabhängigkeiten vom `game`-Unterprojekt zum Projekt der obersten Ebene verschoben.

Dadurch werden keine Testabhängigkeiten mehr der jar hinzugefügt.

Das ist uns in #1487 aufgefallen.

2024-04-22 07:05 UTC, cagix reviewed
@tgrothe Konzeptionelle Frage: Durch die vorgeschlagene Änderung wird für _jedes_ Subprojekt eine JUnit-Dependency erklärt - aber es haben nur zwei Subprojekte tatsächlich Tests.

Ich sehe zwei Varianten:
1. JUnit wird exakt in Game und in Dungeon deklariert (als `testImplementation`.
2. Wir ziehen zusätzlich auch die libGDX- und GSON-Dependency nach außen - dann braucht das nicht mehr "api" sein, sondern "implementation" reicht und diese Dinge stehen einfach alle Subprojekten zur Verfügung?

Dabei ist mir aufgefallen, dass ihr im Dojo-Dungeon die Abhängigkeiten aus "dungeon" als "api" zieht. Warum? Sollen die nach außen exposed werden? Sonst würde "implementation" reichen (analog zum Blockly-Subprojekt)?

2024-04-22 08:15 UTC, tgrothe commented
ich wäre für (2). das hat den vorteil, dass andere subprojekte später auch tests bekommen könnten und es sieht übersichtlicher aus.

und ja, im dojo würde implementation genügen.

2024-04-22 09:27 UTC, cagix commented
> ich wäre für (2). das hat den vorteil, dass andere subprojekte später auch tests bekommen könnten und es sieht übersichtlicher aus.

@tgrothe bitte prüfe das praktisch: verhält sich das projekt noch wie erwartet, wenn wir (2) umsetzen (also run und test für game, für dungeon, für dojo-dungeon; was genau landet im starter.jar; jeweils "clean" zwischendurch)?


> und ja, im dojo würde implementation genügen.

auch hier: bitte mal testen.

2024-04-24 18:36 UTC, tgrothe commented
> Ich sehe zwei Varianten:
> 
>     1. JUnit wird exakt in Game und in Dungeon deklariert (jeweils einzeln als `testImplementation`) und nirgendwo sonst.
> 
>     2. Wir ziehen zusätzlich auch die libGDX- und GSON-Dependency nach außen - dann braucht das nicht mehr "api" sein, sondern "implementation" reicht und diese Dinge stehen einfach allen Subprojekten zur Verfügung?
> 

@cagix Ich hab noch einmal nachgedacht. Option 1 erscheint mir doch sinnvoller. Wir müssen Abhängigkeiten ja nicht dort definieren, wo sie nicht gebraucht werden - und wenn andere Subprojekte auch Tests erhalten sollen, kann man die Abhängigkeiten immer noch hinzufügen, imho.

2024-04-24 19:27 UTC, cagix commented
> > ich wäre für (2). das hat den vorteil, dass andere subprojekte später auch tests bekommen könnten und es sieht übersichtlicher aus.
> 
> 
> 
> @tgrothe bitte prüfe das praktisch: verhält sich das projekt noch wie erwartet, wenn wir (2) umsetzen (also run und test für game, für dungeon, für dojo-dungeon; was genau landet im starter.jar; jeweils "clean" zwischendurch)?
> 
> 
> 
> 
> 
> > und ja, im dojo würde implementation genügen.
> 
> 
> 
> auch hier: bitte mal testen.

hast du das mal systematisch getestet? (mit den zuletzt vorgeschlagenen änderungen)

2024-04-24 19:31 UTC, tgrothe commented
> > > ich wäre für (2). das hat den vorteil, dass andere subprojekte später auch tests bekommen könnten und es sieht übersichtlicher aus.
> > 
> > 
> > @tgrothe bitte prüfe das praktisch: verhält sich das projekt noch wie erwartet, wenn wir (2) umsetzen (also run und test für game, für dungeon, für dojo-dungeon; was genau landet im starter.jar; jeweils "clean" zwischendurch)?
> > > und ja, im dojo würde implementation genügen.
> > 
> > 
> > auch hier: bitte mal testen.
> 
> hast du das mal systematisch getestet? (mit den zuletzt vorgeschlagenen änderungen)

nein, noch nicht, habe nur die unittests durchlaufen lassen ...

ich weiß nicht mehr genau, wie die starter jar angelegt wird und die `jarConverter` sagen mir im moment auch nix ... ich bräuchte einen fahrplan? 😅

2024-04-25 06:56 UTC, cagix commented
> > > > ich wäre für (2). das hat den vorteil, dass andere subprojekte später auch tests bekommen könnten und es sieht übersichtlicher aus.
> > > 
> > > 
> > > @tgrothe bitte prüfe das praktisch: verhält sich das projekt noch wie erwartet, wenn wir (2) umsetzen (also run und test für game, für dungeon, für dojo-dungeon; was genau landet im starter.jar; jeweils "clean" zwischendurch)?
> > > > und ja, im dojo würde implementation genügen.
> > > 
> > > 
> > > auch hier: bitte mal testen.
> > 
> > 
> > hast du das mal systematisch getestet? (mit den zuletzt vorgeschlagenen änderungen)
> 
> nein, noch nicht, habe nur die unittests durchlaufen lassen ...
> 
> ich weiß nicht mehr genau, wie die starter jar angelegt wird und die `jarConverter` sagen mir im moment auch nix ... ich bräuchte einen fahrplan? 😅

build.gradle im dungeon-subprojekt - dort wird ein extra task konfiguriert/definiert. den kannst du nehmen. 

diese seltsamen `jarConverter`-shellskripte/bat-files sollten wir auch mal entfernen (nicht hier!), das ist overkill.

2024-04-26 09:10 UTC, tgrothe commented
@cagix JUnit ist nicht mehr im Starter:

```
./gradlew clean dungeon:buildStarterJar
unzip -l dungeon/build/libs/Starter.jar | grep -i junit
```

Und die Tests funktionieren auch noch alle:

```
./gradlew clean build test

BUILD SUCCESSFUL in 27s
34 actionable tasks: 32 executed, 2 up-to-date
```

Und alle run-Tasks funktionieren ebenfalls.

2024-04-29 05:45 UTC, cagix requested changes

2024-04-29 05:45 UTC, cagix commented on game/build.gradle
> +    // Testing dependencies:
```suggestion
    // JUnit 4 and Mockito for testing
```

2024-04-29 05:45 UTC, cagix commented on dungeon/build.gradle
> +    // Testing dependencies:
```suggestion
    // JUnit 4 and Mockito for testing
```

2024-04-29 05:45 UTC, cagix commented on dojo-dungeon/build.gradle
> +    implementation project(':dungeon')
```suggestion
    api project(':dungeon')
```

2024-04-29 05:45 UTC, cagix commented on dojo-dungeon/build.gradle
> +    implementation project(':dungeon')
@tgrothe So nett und sinnvoll ich diese Änderung an sich finde, sie hat NICHTS in diesem PR zu suchen. (Wieder mal!)

2024-04-29 05:46 UTC, cagix approved these changes

2024-04-29 05:48 UTC, merged