Dojo: Fix: Level 2, Pattern-Abfrage
Dungeon-CampusMinden/Dungeon pull request #1514
Opened 2024-05-03 12:44 UTC by tgrothe

- Als "Zauberer von Patternson" wird die Textur des Ork-Schamanen verwendet
- Die case sensitivity wird bei der Antwort nicht mehr beachtet
- Die Antwort muss nur noch das jeweils gesuchte Pattern enthalten
- Die Fragen werden in zufälliger Reihenfolge gestellt
- Wenn man auf das Textfeld klickt, wird der Text geleert
- Refactoring (zum Beispiel, dass sich die Tür nur einmal öffnen soll)

Draft, closes #1512

2024-05-03 13:07 UTC, tgrothe commented
> 2\. Die Eingabe wird nicht auf verschiedene typische (korrekte bzw. akzeptable) Schreibweisen gematcht. Beispiel: Die richtige Antwort wäre "Foo-Pattern" - dann sollten alle diese Schreibweisen akzeptiert werden: "Foo-Pattern", "Foopattern", "Foo Pattern", "Foo", "Foo-Muster", "Foo-Entwurfsmuster", "Foo Muster", "Foo Entwurfsmuster", jeweils _case-insensitive_

@cagix Würde es ausreichen, nur auf das entsprechende Präfix (Foo) zu prüfen, und jedes beliebige Anhängsel zu erlauben? Das wäre eine Vereinfachung.

2024-05-03 14:48 UTC, cagix commented
@tgrothe danke, dass du hier gleich drauf springst. es eilt aber nicht, das level ist erst in ein paar wochen dran. es sollte so zum 12.6. herum fertig sein.

2024-05-03 14:52 UTC, tgrothe commented
> präfix weiss ich nicht, aber vielleicht reicht es, wenn das gesuchte wort ein teilstring der bereinigten eingabe ist? (bereinigt um groß/klein, leerzeichen raus, bindestriche raus)

okay, können wir ja so machen. :)

> @tgrothe danke, dass du hier gleich drauf springst. es eilt aber nicht, das level ist erst in ein paar wochen dran. es sollte so zum 12.6. herum fertig sein.

kein problem, bis dahin bekommen wir das "schön". :D

2024-05-03 23:41 UTC, tgrothe commented
@cagix Können wir #1513 auch in diesem pr umsetzen?

2024-05-04 05:43 UTC, cagix commented
> @cagix Können wir #1513 auch in diesem pr umsetzen?

lass mal trennen. das hier ist eher ein fix, das andere ein "feature". sowas möchte ich in der history erkennen (und ggf. separat umherschieben) können.

2024-05-04 06:19 UTC, cagix requested changes
noch nicht ganz da:

- trennung der einzelnen unterschiedlichen aspekte in separate pr's (textur, string-vergleich, clickhandler)
- stringvergleich entspricht noch nicht der aufgabe - hier würde ich der einfachheit halber auf `string#matches` umstellen
- was machst du da mit den expectedindizes? das ist super komplex, ein einfaches `rand` mit dem bereich der lösungsliste plus vergleich mit dem aktuellen current (und bei gleichheit ein +1 % length) sollte doch völlig ausreichen, um die nächste frage zufällig zu bestimmen?
- eine änderung gehört hier nicht her...

2024-05-04 06:19 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/riddle/Fragen_Pattern.java
> +    zauberer.add(new DrawComponent(new SimpleIPath("character/monster/orc_shaman")));
diese änderung ist ok, sollte aber in einen eigenen pr. 

bitte auch den aufgabentext entsprechend anpassen in dem pr.

2024-05-04 06:19 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/riddle/Fragen_Pattern.java
> +      String answer = rawAnswer.trim().toLowerCase(Locale.ROOT);
trim entfernt nur leerzeichen, und nur am anfang/ende.

d.h. bindestriche und interne leerzeichen sind immer noch da.

ich möchte einen alternativen ansatz vorschlagen: betrachte die lösungsstrings als regexp und ergänze noch am anfang/ende ein `.*?` für beliebige zeichen. unten machst du dann statt `contains` ein `matches`.

2024-05-04 06:19 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/riddle/Fragen_Pattern.java
> +      if (answer.contains(expectedPatterns[expectedPatternsIndices.get(currentPatternIndex)])) {
s.o.: ich würde hier eher mit `marches` arbeiten.

2024-05-04 08:03 UTC, tgrothe commented on dojo-dungeon/src/starter/DojoStarter.java
> +    Game.currentLevel(allLevels[1].buildRooms.get(1).levelRoom.level());
ja. das war (oder ist) nur drin, damit das level/den raum einfacher ausprobieren kann, ob alles stimmt.

2024-05-04 08:13 UTC, tgrothe commented
> * was machst du da mit den expectedindizes? das ist super komplex, ein einfaches `rand` mit dem bereich der lösungsliste plus vergleich mit dem aktuellen current (und bei gleichheit ein +1 % length) sollte doch völlig ausreichen, um die nächste frage zufällig zu bestimmen?

leider nicht ganz. bei einem einfachen rand kann es vorkommen, dass die gleiche frage noch einmal gestellt wird.

neuer ansatz: wir haben eine liste mit indices (aufsteigende folge, 0, 1, 2 usw.). diese wird am anfang einmal gemischt. dadurch bekommen wir eine zufällige reihenfolge der fragen, wobei keine frage doppelt gestellt wird.

ich finde das nicht zu kompliziert, es sieht nur kompliziert aus, wegen der stream-schreibweise und den ctor-init-block ...

könnte das bitte so bleiben? andernfalls könnte ich auch einen iterator dafür schreiben.

> * eine änderung gehört hier nicht her...

dann im extra pull request.

2024-05-04 08:37 UTC, tgrothe commented on dungeon/src/task/game/hud/QuizDialogDesign.java
Ich werde einzelne Pull-Requests dafür aufmachen. :)

2024-05-04 09:44 UTC, cagix commented on dojo-dungeon/src/starter/DojoStarter.java
> +    Game.currentLevel(allLevels[1].buildRooms.get(1).levelRoom.level());
bitte nicht einchecken/pushen. sowas verwirrt beim review, weil die absicht dahinter ja nicht offensichtlich ist.

2024-05-04 09:49 UTC, cagix commented
> > * was machst du da mit den expectedindizes? das ist super komplex, ein einfaches `rand` mit dem bereich der lösungsliste plus vergleich mit dem aktuellen current (und bei gleichheit ein +1 % length) sollte doch völlig ausreichen, um die nächste frage zufällig zu bestimmen?
> 
> 
> 
> leider nicht ganz. bei einem einfachen rand kann es vorkommen, dass die gleiche frage noch einmal gestellt wird.
> 
> 
> 
> neuer ansatz: wir haben eine liste mit indices (aufsteigende folge, 0, 1, 2 usw.). diese wird am anfang einmal gemischt. dadurch bekommen wir eine zufällige reihenfolge der fragen, wobei keine frage doppelt gestellt wird.
> 
> 
> 
> ich finde das nicht zu kompliziert, es sieht nur kompliziert aus, wegen der stream-schreibweise und den ctor-init-block ...
> 
> 
> 
> könnte das bitte so bleiben? andernfalls könnte ich auch einen iterator dafür schreiben.
> 


ehrlich gesagt habe ich das nie als problem gesehen. wenn alle fragen durch sind, präsentierst du ja sowieso wieder die erste frage, auch jetzt.

so lange sicher gestellt ist, dass man nicht exakt die selbe frage 2x hintereinander bekommt, reicht das völlig.

aus meiner sicht blähst du die codebasis auf und packst schlecht les- und wartbaren code ins projekt, ohne damit ein echtes problem zu fixen. sowas möchte ich nicht (ich bin nämlich der idiot, der das pflegen muss).

2024-05-04 09:56 UTC, tgrothe commented
> > > * was machst du da mit den expectedindizes? das ist super komplex, ein einfaches `rand` mit dem bereich der lösungsliste plus vergleich mit dem aktuellen current (und bei gleichheit ein +1 % length) sollte doch völlig ausreichen, um die nächste frage zufällig zu bestimmen?
> > 
> > 
> > leider nicht ganz. bei einem einfachen rand kann es vorkommen, dass die gleiche frage noch einmal gestellt wird.
> > neuer ansatz: wir haben eine liste mit indices (aufsteigende folge, 0, 1, 2 usw.). diese wird am anfang einmal gemischt. dadurch bekommen wir eine zufällige reihenfolge der fragen, wobei keine frage doppelt gestellt wird.
> > ich finde das nicht zu kompliziert, es sieht nur kompliziert aus, wegen der stream-schreibweise und den ctor-init-block ...
> > könnte das bitte so bleiben? andernfalls könnte ich auch einen iterator dafür schreiben.
> 
> ehrlich gesagt habe ich das nie als problem gesehen. wenn alle fragen durch sind, präsentierst du ja sowieso wieder die erste frage, auch jetzt.
> 
> so lange sicher gestellt ist, dass man nicht exakt die selbe frage 2x hintereinander bekommt, reicht das völlig.
> 
> aus meiner sicht blähst du die codebasis auf und packst schlecht les- und wartbaren code ins projekt, ohne damit ein echtes problem zu fixen. sowas möchte ich nicht (ich bin nämlich der idiot, der das pflegen muss).
> 
> edit: tut mir leid für die energie, die du da reingesteckt hast. aber sprich extra ideen bitte vorher ab, dann lässt sich solche blindleistung vermeiden.

Der Lerneffekt ist doch geringer, wenn immer die gleichen Fragen in der gleichen Reihenfolge gestellt werden ... oder bin ich da auf dem Holzweg? Ich habe dafür ein Ticket #1518 erstellt. Ich möchte das noch einmal "besser wartbar" umsetzen, aber nicht in diesem pr.

2024-05-04 10:04 UTC, cagix commented
> > > > * was machst du da mit den expectedindizes? das ist super komplex, ein einfaches `rand` mit dem bereich der lösungsliste plus vergleich mit dem aktuellen current (und bei gleichheit ein +1 % length) sollte doch völlig ausreichen, um die nächste frage zufällig zu bestimmen?
> 
> > > 
> 
> > > 
> 
> > > leider nicht ganz. bei einem einfachen rand kann es vorkommen, dass die gleiche frage noch einmal gestellt wird.
> 
> > > neuer ansatz: wir haben eine liste mit indices (aufsteigende folge, 0, 1, 2 usw.). diese wird am anfang einmal gemischt. dadurch bekommen wir eine zufällige reihenfolge der fragen, wobei keine frage doppelt gestellt wird.
> 
> > > ich finde das nicht zu kompliziert, es sieht nur kompliziert aus, wegen der stream-schreibweise und den ctor-init-block ...
> 
> > > könnte das bitte so bleiben? andernfalls könnte ich auch einen iterator dafür schreiben.
> 
> > 
> 
> > ehrlich gesagt habe ich das nie als problem gesehen. wenn alle fragen durch sind, präsentierst du ja sowieso wieder die erste frage, auch jetzt.
> 
> > 
> 
> > so lange sicher gestellt ist, dass man nicht exakt die selbe frage 2x hintereinander bekommt, reicht das völlig.
> 
> > 
> 
> > aus meiner sicht blähst du die codebasis auf und packst schlecht les- und wartbaren code ins projekt, ohne damit ein echtes problem zu fixen. sowas möchte ich nicht (ich bin nämlich der idiot, der das pflegen muss).
> 
> > 
> 
> > edit: tut mir leid für die energie, die du da reingesteckt hast. aber sprich extra ideen bitte vorher ab, dann lässt sich solche blindleistung vermeiden.
> 
> 
> 
> Der Lerneffekt ist doch geringer, wenn immer die gleichen Fragen in der gleichen Reihenfolge gestellt werden ... oder bin ich da auf dem Holzweg? Ich habe dafür ein Ticket #1518 erstellt. Ich möchte das noch einmal "besser wartbar" umsetzen, aber nicht in diesem pr.

mit dem lernerfolg hast du recht, aber dazu musst du einfach nur aus den fragen zufällig auswählen und einfach nur dafür sorgen, dass beim neu würfeln nicht der selbe fragenindex von eben nochmal genommen wird. das reicht, und mehr möchte ich nicht. damit ist dieser punkt für mich beendet, bitte investiere dort keine zeit rein.

2024-05-05 09:58 UTC, tgrothe commented
Es geht weiter in #1521 #1522 #1523 und #1524. -> close

2024-05-05 09:58 UTC, closed without merging