Dojo: Level 2, MyImp: Gestaltung des Vorgabe-Codes
Dungeon-CampusMinden/Dungeon pull request #1525
Opened 2024-05-06 07:49 UTC by tgrothe

Änderungen:

1. `modifyMyImp` wurde entfernt
2. `createEntit` wurde ausgelagert
3. "TODO: <...>" wurde hinzugefügt
3.1. Die Reihenfolge der Methoden in `MyImp` wurde angepasst
4. Dem Inventar des Helden soll ein Gesundheitstrank hinzugefügt werden
5. Die Namen der Methoden in `MyImp` wurden angepasst

closes #1515

2024-05-06 07:52 UTC, tgrothe commented
@cagix Ich habe versucht, mich diesmal (strikt) an "den Fahrplan" zu halten, und alles nach den Vorstellungen umzusetzen. Bitte schaue dir das einmal an.

Ich bin erst heute Nachmittag wieder zurück und habe dann Zeit dafür.

2024-05-07 16:00 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
den klassennamen finde ich irgendwie irreführend. in anlehnung zu den anderen klassen/räumen im selben package: wie wäre es mit "MyImpRoom"?

2024-05-07 16:01 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +    ic.add(new ItemResourceBerry());
??? verstehe ich nicht?

2024-05-07 19:38 UTC, tgrothe commented on dojo-dungeon/src/dojo/monster/MyImp.java
> +  /** Adds new potion health to heros inventory. */
Ja, ich denke, "health potion" klingt irgendwie "richtiger" (und weniger holprig). Auch, wenn es den Schwierigkeitsgrad erhöht, ich würde das noch gerne ändern.

2024-05-07 19:41 UTC, tgrothe commented on dojo-dungeon/src/dojo/monster/MyImp.java
> +  public static void addNewPotionHealthToHerosInventory() {
Ok, Entity wird übergeben werden und -Hero und -Imp...

2024-05-07 19:43 UTC, tgrothe commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +    ic.add(new ItemResourceBerry());
Nein, muss es nicht, dann nehme ich die "dropping logic" auch wieder heraus (vorsichtshalber, ich weiß nämlich net, was geschieht, wenn etwas gedroppt werden soll und das Inventar leer ist...)

2024-05-07 19:53 UTC, cagix commented on dojo-dungeon/src/dojo/monster/MyImp.java
> +  /** Adds new potion health to heros inventory. */
dann los 😀

2024-05-08 11:04 UTC, tgrothe commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +    ic.add(new ItemResourceBerry());
-> [a8cb39f](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1525/commits/a8cb39f401dbbada9194237b1c901cdb57775f9b)

2024-05-08 11:04 UTC, tgrothe commented on dojo-dungeon/src/dojo/monster/MyImp.java
> +  public static void addNewPotionHealthToHerosInventory() {
-> [a8cb39f](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1525/commits/a8cb39f401dbbada9194237b1c901cdb57775f9b)

2024-05-08 11:04 UTC, tgrothe commented on dojo-dungeon/src/dojo/monster/MyImp.java
>  public class MyImp {
-> [a8cb39f](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1525/commits/a8cb39f401dbbada9194237b1c901cdb57775f9b)

2024-05-08 11:05 UTC, tgrothe commented on dojo-dungeon/src/dojo/monster/MyImp.java
> +  public static void disableImpGodMode(Entity myImp) {
-> [a8cb39f](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1525/commits/a8cb39f401dbbada9194237b1c901cdb57775f9b)

2024-05-08 11:05 UTC, tgrothe commented on dojo-dungeon/src/dojo/monster/MyImp.java
> +  public static void setImpHealthTo25(Entity myImp) {
-> [a8cb39f](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1525/commits/a8cb39f401dbbada9194237b1c901cdb57775f9b)

2024-05-08 11:05 UTC, tgrothe commented on dojo-dungeon/src/dojo/monster/MyImp.java
> +  public static void increaseImpSpeed(Entity myImp) {
-> [a8cb39f](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1525/commits/a8cb39f401dbbada9194237b1c901cdb57775f9b)

2024-05-08 11:05 UTC, tgrothe commented on dojo-dungeon/src/dojo/monster/MyImp.java
> +  /** Adds new potion health to heros inventory. */
-> [a8cb39f](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1525/commits/a8cb39f401dbbada9194237b1c901cdb57775f9b)

2024-05-08 11:05 UTC, tgrothe commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
-> [a8cb39f](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1525/commits/a8cb39f401dbbada9194237b1c901cdb57775f9b)

2024-05-08 11:08 UTC, tgrothe commented
@cagix Es sollte jetzt so passen. Die Pull-Request-Beschreibung habe ich auch editiert. Bitte noch einmal schauen.

2024-05-11 12:57 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
ist das ein anzeigeproblem oder so? bei mir in der app wird immer noch der alte name angezeigt?!

2024-05-11 13:06 UTC, cagix requested changes
sieht dich schon ganz gut aus ... ein paar kleinigkeiten noch...

2024-05-11 13:06 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +      "src/dojo/utils/studentTasks/modifyEntities/ModifyEntities";
sollte der pfad aus sicht der studis geschrieben sein, also noch mit "dojo-dungeon" vorneweg?

2024-05-11 13:06 UTC, cagix commented on dojo-dungeon/src/dojo/utils/studentTasks/modifyEntities/ModifyEntities.java
> +   * @param entity the entity (imp) to modify
nimm den imp hier bitte (komplett) raus.

2024-05-11 13:06 UTC, cagix commented on dojo-dungeon/src/dojo/utils/studentTasks/modifyEntities/ModifyEntities.java
> +   * @param entity the entity (imp) to modify
nimm den imp hier bitte (komplett) raus.

2024-05-11 13:06 UTC, cagix commented on dojo-dungeon/src/dojo/utils/studentTasks/modifyEntities/ModifyEntities.java
> +   * @param entity the entity (imp) to modify
nimm den imp hier bitte (komplett) raus.

2024-05-11 13:06 UTC, cagix commented on dojo-dungeon/src/dojo/utils/studentTasks/modifyEntities/ModifyEntities.java
> +   * Adds a new health potion to the heros inventory.
nimm den hero hier bitte (komplett) raus.

2024-05-11 13:06 UTC, cagix commented on dojo-dungeon/src/dojo/utils/studentTasks/modifyEntities/ModifyEntities.java
> +   * @param entity the entity (hero) to modify
nimm den hero hier bitte (komplett) raus.

2024-05-11 13:06 UTC, cagix commented on dojo-dungeon/src/dojo/utils/studentTasks/modifyEntities/ModifyEntities.java
> +    // TODO: Add a new health potion to the heros inventory.
nimm den hero hier bitte (komplett) raus.

2024-05-11 13:06 UTC, cagix commented on dojo-dungeon/src/dojo/utils/studentTasks/modifyEntities/ModifyEntities.java
> +/** Class to modify game entities. */
hier könnte noch ein satz hinzugefügt werden, dass diese die klasse ist, welche die studis in raum x in level y ergänzen sollen. dann wissen sie, dass sie richtig sind ...

2024-05-11 15:44 UTC, tgrothe commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
Kein Anzeigeproblem, ich hatte den Klassennamen noch nicht geändert. :) Ich dachte erst, nur der Paketpfad sollte geändert werden ...

2024-05-12 11:07 UTC, tgrothe commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +      "src/dojo/utils/studentTasks/modifyEntities/ModifyEntities";
Nein, den Pfad sehen die Studis nicht, die Studis sehen nur den (fully-qualified) class name.

Soll stattdessen der Pfad zur Datei gezeigt werden?

2024-05-12 11:19 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +      "src/dojo/utils/studentTasks/modifyEntities/ModifyEntities";
neee. ich dachte nur, das wäre hier der text für die studis. etwas verwirrend, wenn du mich fragst ...

2024-05-12 11:27 UTC, tgrothe commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +      "src/dojo/utils/studentTasks/modifyEntities/ModifyEntities";
Schau mal bitte, ob das jetzt so "stimmig" ist.

2024-05-12 11:30 UTC, cagix commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +      "src/dojo/utils/studentTasks/modifyEntities/ModifyEntities";
die variablen sind jetzt besser benannt. danke.

aber es sind trotzdem noch drei variablen mit fast identischem inhalt? d.h. bei anpassungen muss man alle drei richtig anpassen? kann man das evtl. auf eine variable reduzieren?

2024-05-12 11:32 UTC, tgrothe commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +      "src/dojo/utils/studentTasks/modifyEntities/ModifyEntities";
> aber es sind trotzdem noch drei variablen mit fast identischem inhalt? d.h. bei anpassungen muss man alle drei richtig anpassen? kann man das evtl. auf eine variable reduzieren?

ja, das geht, moment.

2024-05-12 15:05 UTC, tgrothe commented on dojo-dungeon/src/dojo/rooms/rooms/boss/Implement_MyImp.java
> +      "src/dojo/utils/studentTasks/modifyEntities/ModifyEntities";
sry, war kurz net am pc ...

nun geht's! -> 13f70aae0c5b6823a7342cd53f0e5fa0a099bcec

2024-05-13 05:59 UTC, cagix approved these changes

2024-05-13 06:58 UTC, merged