Dojo: add a few more additional patterns to the pattern question in the second level
Dungeon-CampusMinden/Dungeon pull request #1526
Opened 2024-05-06 15:43 UTC by tgrothe

Für die Pattern-Frage gibt es bisher genau zwei Fragen, einmal Visitor und einmal Observer. 

Dieser PR fügt weitere Beispiele hinzu:
- Es wurden die Beispiele: Kompositum, Adapter und Singleton hinzugefügt.
- Es wurde ein Nicht-Pattern-Beispiel hinzugefügt.
- Es wurde je ein weiteres Beispiel für Visitor und Observer ergänzt.

Alle bisher nicht behandelten Pattern werden sowohl unter ihrem Namen als auch als "none" erkannt/akzeptiert, da die Studierenden diese bisher noch nicht kennen können. 

closes #1513

2024-05-07 16:08 UTC, cagix reviewed
hab ich vielleicht nicht wirklich gut beschrieben: in prog2 bespreche ich nur visitor und observer (jedenfalls bis zum zeitpunkt, wo sie diese aufgabe lösen sollen). in prog1 waren bereits strategy und singleton dran.

d.h. composite und adapter _können_ sie gar nicht erkennen. das müsste also auch als "no pattern" erlaubt sein (für den fall, dass es doch jemand kennt, müsstest du tatsächlich ein "oder" einbauen wie bei composite).

kannst du bitte noch ein paar zusätzliche beispiele für observer und visitor basteln? gerne auch irgendwie verschränkt o.ä. (also die kästchen anders angeordnet), so dass man die struktur nicht sofort sieht? kannst du dir morgen ggf. noch wen von den anderen tutoren schnappen, damit du hier nicht alleine bist?

der string für "kein pattern" ist noch zu lang. meine erfahrung sagt mit, dass das nur 10% korrekt eintippen können - die anderen sind dann frustriert. kannst du hier irgendwas kürzeres finden, am besten auch als ein wort? 


edit: ich finde die neuen beispiele nicht schlecht, lass die drin. mir ging es nur darum, dass die zum zeitpunkt der aufgabe einfach nicht bekannt sind.

2024-05-09 07:47 UTC, tgrothe commented
> 
> d.h. composite und adapter _können_ sie gar nicht erkennen. das müsste also auch als "no pattern" erlaubt sein (für den fall, dass es doch jemand kennt, müsstest du tatsächlich ein "oder" einbauen wie bei composite).

Ok, das wird als Antwortmöglichkeit hinzugefügt.

> 
> der string für "kein pattern" ist noch zu lang. meine erfahrung sagt mit, dass das nur 10% korrekt eintippen können - die anderen sind dann frustriert. kannst du hier irgendwas kürzeres finden, am besten auch als ein wort?

😀 musste doch etwas lachen. Wie wäre es mit "no pattern" und "" (leere Eingabe), wenn kein Pattern gesucht ist?

> 
> edit: ich finde die neuen beispiele nicht schlecht, lass die drin. mir ging es nur darum, dass die zum zeitpunkt der aufgabe einfach nicht bekannt sind.

bleiben drin, aber ich füge noch weitere Beispiele für visitor und observer hinzu.

@Dungeon-CampusMinden/tutors hat von euch vielleicht jemand Zeit oder Lust hierzu? Im Prinzip müssten nur die Plantuml source files mit Beispielen erstellt werden. IJ hat auch ein Plantuml-Plugin, um die Vorschau zu sehen und die PNGs zu erzeugen. Wenn ja, bitte kurz melden.

2024-05-11 05:07 UTC, tgrothe commented
@cagix Ich glaube, nun sind erst mal genug Beispiele dabei. Wenn #1523 durch ist, dann könnte man hier mergen.

2024-05-15 06:24 UTC, cagix requested changes
Das reicht erstmal an Beispielen/Fragen.

Drei Dinge:

1. Bitte ergänze wie besprochen ein "none" für alle Pattern, die nicht Observer oder Visitor sind. 
2. Bitte nenne die Klassen/Methoden in Visitor/Observer nicht "Visitor" bzw. "Observer", sondern passend zur Domäne. Also beispielsweise sowas wie "Renderer" oder so beim Dokumentenbeispiel.
3. Schaue bitte nochmal in die Vorlesung, welche Darstellung dort für Visitor/Observer genutzt wird und passe Deine Darstellung entsprechend an. Ich habe die Rollen-Beziehungen beispielsweise bisher nicht verwendet, und afaik sind die auch in PR1 nicht dran gewesen. Nutze ggf. Kommentare.

2024-05-15 11:12 UTC, tgrothe commented
> 2\. Bitte nenne die Klassen/Methoden in Visitor/Observer nicht "Visitor" bzw. "Observer", sondern passend zur Domäne. Also beispielsweise sowas wie "Renderer" oder so beim Dokumentenbeispiel.

Hm, hast du vielleicht eine Idee, wie ich die (explizite/implizite) Nennung von "Visitor" oder "Observer" vermeiden kann?

Ich schaue heute Nachmittag mal danach.

2024-05-18 07:18 UTC, tgrothe commented
> 3\. Schaue bitte nochmal in die Vorlesung, welche Darstellung dort für Visitor/Observer genutzt wird und passe Deine Darstellung entsprechend an. Ich habe die Rollen-Beziehungen beispielsweise bisher nicht verwendet, und afaik sind die auch in PR1 nicht dran gewesen. Nutze ggf. Kommentare.

Guten Morgen @cagix , also: -Rollen-Beziehungen an allen Assoziationen? Dürfen die > und < Zeichen erhalten bleiben, um die Leserichtung hervorzuheben? Und sollen die Kommentare an den Klassen vielleicht ganz weg?

2024-05-20 06:43 UTC, tgrothe commented
@cagix Bitte noch einmal schauen. Ich bin die Vorlesungen noch einmal durchgegangen und habe die Diagramme angepasst. Zudem sollte es jetzt auch (strikt) UML-konform (https://en.wikipedia.org/wiki/Class_diagram#Instance-level_relationships) sein.

2024-05-21 16:56 UTC, cagix approved these changes
Danke. Das sollte so gehen :)

2024-05-21 16:56 UTC, merged