DevDungeon
Dungeon-CampusMinden/Dungeon pull request #1608
Opened 2024-07-31 16:01 UTC by Flamtky

WIP

2024-07-31 18:53 UTC, Flamtky commented
@cagix Ich würde schonmal den PR auf ready setzen, sodass du schonmal ein Review mir geben könntest. Den Text/Titel für den PR würde ich dann morgen Abend ergänzen.

2024-08-01 09:20 UTC, cagix requested changes
🥳

ein paar kleinere kommentare anbei. 

willst du die animationen für necromancer und goo und goo-small wirklich im dungeon und nicht im devdungeon einkippen? mir ist es egal - aber im readme fehlt so noch die angabe, von wem das ist (also von dir)?

ich habe das spiel noch nicht gestartet. kannst du spaßeshalber mal im projekt die .idea und .gradle ordner löschen und in deinem homeverzeichnis die .gradle und .m2 ordner auch und dann das projekt neu in idea aufmachen und über gradle starten?

hast du mal einen diff zw. dem hiesigen devdungeon-pr und deinem ba-repo gemacht, damit nix übersehen wird? aber vermutlich ist das nicht so richtig sinnvoll, weil es noch zu viele änderungen und verschiebungen gab, oder?

2024-08-01 09:20 UTC, cagix commented on devDungeon/build.gradle
> +    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
hier fehlt noch ein newline :)

2024-08-01 09:20 UTC, cagix commented on devDungeon/src/entities/BossAttackSkills.java
> +  public static final int FIRE_SHOCKWAVE_DAMAGE = 1;
soll das wirklich alles "public" sein oder ist das nur ein versehen?

2024-08-01 09:20 UTC, cagix commented on devDungeon/src/item/effects/BurningEffect.java
> +
```suggestion
```

2024-08-01 09:20 UTC, cagix commented on devDungeon/src/utils/ArrayUtils.java
> +    return list.subList(0, n);
was passiert hier eigentlich, wenn "n" zu groß ist?

2024-08-01 17:49 UTC, cagix reviewed
@Flamtky beim javadoc zum array-check stimmt irgendwie die reihenfolge nicht?

```
[ant:checkstyle] [WARN] /home/runner/work/Dungeon/Dungeon/devDungeon/src/utils/ArrayUtils.java:18: Block tags have to appear in the order '[@author, @version, @param, @return, @throws, @exception, @see, @since, @serial, @serialField, @serialData, @deprecated]'. [AtclauseOrder]
```

2024-08-01 17:56 UTC, Flamtky commented
> willst du die animationen für necromancer und goo und goo-small wirklich im dungeon und nicht im devdungeon einkippen? mir ist es egal - aber im readme fehlt so noch die angabe, von wem das ist (also von dir)?

Ist bereits in der Readme. Ich habe nur Quellen verwendet die schon verwendet wurden. Und wegen der Position würde ich sagen das es Sinn macht das im Dungeon zu haben? So liegen alle Texturen für Monster zusammen und man könnte die einfach ergänzen im Framework, für andere Spiele.

> ich habe das spiel noch nicht gestartet. kannst du spaßeshalber mal im projekt die .idea und .gradle ordner löschen und in deinem homeverzeichnis die .gradle und .m2 ordner auch und dann das projekt neu in idea aufmachen und über gradle starten?

Mache ich mal gleich.

> hast du mal einen diff zw. dem hiesigen devdungeon-pr und deinem ba-repo gemacht, damit nix übersehen wird? aber vermutlich ist das nicht so richtig sinnvoll, weil es noch zu viele änderungen und verschiebungen gab, oder?

Habe immer anhand eines Diff gearbeitet. Ich werde trotz der neuen Änderungen einmal alles lokal durchgehen.

2024-08-01 18:35 UTC, cagix commented
> > willst du die animationen für necromancer und goo und goo-small wirklich im dungeon und nicht im devdungeon einkippen? mir ist es egal - aber im readme fehlt so noch die angabe, von wem das ist (also von dir)?
> 
> 
> 
> Ist bereits in der Readme. Ich habe nur Quellen verwendet die schon verwendet wurden. Und wegen der Position würde ich sagen das es Sinn macht das im Dungeon zu haben? So liegen alle Texturen für Monster zusammen und man könnte die einfach ergänzen im Framework, für andere Spiele.

den gedanken kann ich gut nachvollziehen. am ende ist es deine entscheidung :)  ich bin fein mit beiden varianten.


> 
> 
> 
> > ich habe das spiel noch nicht gestartet. kannst du spaßeshalber mal im projekt die .idea und .gradle ordner löschen und in deinem homeverzeichnis die .gradle und .m2 ordner auch und dann das projekt neu in idea aufmachen und über gradle starten?
> 
> 
> 
> Mache ich mal gleich.

ta!


> 
> 
> 
> > hast du mal einen diff zw. dem hiesigen devdungeon-pr und deinem ba-repo gemacht, damit nix übersehen wird? aber vermutlich ist das nicht so richtig sinnvoll, weil es noch zu viele änderungen und verschiebungen gab, oder?
> 
> 
> 
> Habe immer anhand eines Diff gearbeitet. Ich werde trotz der neuen Änderungen einmal alles lokal durchgehen.

ah, perfekt! 👍

2024-08-01 18:55 UTC, Flamtky commented
> > > willst du die animationen für necromancer und goo und goo-small wirklich im dungeon und nicht im devdungeon einkippen? mir ist es egal - aber im readme fehlt so noch die angabe, von wem das ist (also von dir)?
> > 
> > 
> > Ist bereits in der Readme. Ich habe nur Quellen verwendet die schon verwendet wurden. Und wegen der Position würde ich sagen das es Sinn macht das im Dungeon zu haben? So liegen alle Texturen für Monster zusammen und man könnte die einfach ergänzen im Framework, für andere Spiele.
> 
> den gedanken kann ich gut nachvollziehen. am ende ist es deine entscheidung :) ich bin fein mit beiden varianten.

Dann belasse ich es so, notfalls einfach die neuen Texturen in der Random Textur Auswahl (`MONSTER_FILE_PATHS` in `MonsterFactory`) ergänzen 😆

> > > ich habe das spiel noch nicht gestartet. kannst du spaßeshalber mal im projekt die .idea und .gradle ordner löschen und in deinem homeverzeichnis die .gradle und .m2 ordner auch und dann das projekt neu in idea aufmachen und über gradle starten?
> > 
> > 
> > Mache ich mal gleich.
> 
> ta!

Ich habe es grade getestet und das Spiel läuft. Die JAR auch.

> > > hast du mal einen diff zw. dem hiesigen devdungeon-pr und deinem ba-repo gemacht, damit nix übersehen wird? aber vermutlich ist das nicht so richtig sinnvoll, weil es noch zu viele änderungen und verschiebungen gab, oder?
> > 
> > 
> > Habe immer anhand eines Diff gearbeitet. Ich werde trotz der neuen Änderungen einmal alles lokal durchgehen.
> 
> ah, perfekt! 👍

Alle lokalen Änderung die noch habe sind irrelevante oder überflüssige Änderungen. Ich maximal noch einen Workaround für #1609. 

Dann werde ich mal den DevDungeon mergen!

2024-08-01 18:56 UTC, merged

2024-08-01 19:07 UTC, cagix commented
@Flamtky you did great 😻👏🥇🏆