Add new DSL
Dungeon-CampusMinden/Dungeon pull request #1631
Opened 2024-09-04 18:04 UTC by lukasweidich

2024-09-04 19:23 UTC, cagix commented
Hmmm, irgendwas stimmt nicht - er versucht, eine Uraltversion von Gradle (v4.5) zu laden? Ich hab grad nochmal im Master geschaut, da passt es und er lädt eine v8.x ...

2024-09-04 19:30 UTC, cagix requested changes

2024-09-04 19:30 UTC, cagix commented on gradle/wrapper/gradle-wrapper.properties
@lukasweidich kannst du bitte diese änderungen im  wrapper zurückdrehen? das lädt eine uraltversion von gradle, die mit dem aktuellen jdk nicht klarkommt ... (wirkt auf mich auch eher wie ein versehentlicher commit?)

2024-09-26 06:23 UTC, cagix commented on gradle/wrapper/gradle-wrapper.properties
ping

2024-09-26 06:24 UTC, cagix commented on gradle/wrapper/gradle-wrapper.properties
@lukasweidich ping

2024-09-27 10:52 UTC, cagix commented
@bcg7 hier die grammatik: [dungeon/src/newdsl/antlr/DSL.g4](https://github.com/lukasweidich/Dungeon/blob/master/dungeon/src/newdsl/antlr/DSL.g4)

2024-09-28 07:41 UTC, lukasweidich commented on gradle/wrapper/gradle-wrapper.properties
Ist reverted, gradle 8.10. wird wieder verwendet

2024-10-12 09:19 UTC, cagix reviewed
Beobachtungen:

Das Projekt bringt viele neue Ideen mit sich, ist aber noch nicht ganz fertig. Insbesondere die Einbindung an den Dungeon ist noch bruchstückhaft (wenn ich die Erklärungen in der schriftlichen Arbeit noch korrekt in Erinnerung habe). 

Ich sehe 2 Optionen:

1. Merge in einen Feature-Branch als Ideen-Pool.
2. Überarbeitung dieses Branches (Build, Änderungen an existierenden Dateien) und Merge in den Master als Basis für aufbauende Arbeiten.

Für (2) müssten ein paar Dinge gemacht werden:
- Das Projekt/der PR baut nicht. 
- Es wurden einige existierende Dateien geändert, so dass alte Funktionalität nicht mehr gegeben ist (zb. Starter und TaskSelector und Quiz; aber auch build.gradle in game oder LevelGraphGenerator ...).
- Das Gesamtprojekt sollte nochmal in der Struktur überdacht werden. Zumindest sollte diese Arbeit mit der neuen DSL in ein eigenes Gradle-Subprojekt und nicht ins alte `dungeon`-Subprojekt gemergt werden.

2024-11-06 08:24 UTC, cagix approved these changes
Spannende Arbeit! Insbesondere der Teil zum Sprachdesign ist erfrischend 👍 Die Einbindung in den Dungeon benötigt aus meiner Sicht allerdings noch einige Arbeit.

Deshalb merge ich die Arbeit zunächst in einen Feature-Branch, bis jemand die Zeit für eine vernünftige Integration findet.

2024-11-06 08:25 UTC, merged