Extend blockly project with new blocks and visualization of variables and arrays in the dungeon
Dungeon-CampusMinden/Dungeon pull request #1644
Opened 2024-10-04 19:27 UTC by CodingJosh42

This PR extends the existing Blockly project with new blocks and also adds visualization of variables and arrays in the dungeon.

New Blockly Blocks:

1. Arrays
2. Func defs
3. Func calls
4. While-Loops
5. If-Statement (revised, can be nested now)
6. Repeat-Loop (revised, can be nested now)
7. Conditions: Logic operator, compare operators
8. Expressions

Visualization in the dungeon:
Display varaibles and arrays in the dungeon with a special HUD.

2024-10-11 11:28 UTC, cagix commented on blockly/build.gradle
> +  testImplementation supportDependencies.junit
```suggestion
  implementation project(':dungeon')
  
  // ANTLR version 4 for DSL Grammar
  antlr supportDependencies.antlr

    // JUnit 4 and Mockito for testing
  testImplementation supportDependencies.junit
```

2024-10-11 11:49 UTC, cagix requested changes
Schöne Arbeit!

Ein paar Beobachtungen/Fragen:

- [x] Wo kommen die neuen Assets her? Insbesondere die neuen Monster und die Tile-Sets? Da muss ins Haupt-Readme noch ein Eintrag bzgl. Herkunft und ggf. Lizenz. => je ein Readme.md mit dazu mit Bemerkung, dass die Dateien Kopien aus dem Dungeon-Ordner XYZ sind.

- [x] Ich würde ungern den von ANTLR generierten Code einchecken. Wir haben im dungeon eine Konfiguration, die das beim Build unter `build/generated-src/antlr/` packt und auch den Classpath korrekt setzt. Alternativ findest Du hier ein Beispiel: https://github.com/Compiler-CampusMinden/CB-Vorlesung-Bachelor/tree/master/homework/src/sample_project

- [X] ~~Du hast einige kleine Videos auf YouTube verlinkt. Da die in Deinem Namespace liegen: Kriegt Du die als Gif exportiert und hier als Bild eingebunden?~~ => Das sind Links auf fremde kleine Videos - kann so bleiben.

- [x] Der Level-Designer liegt parallel zu Blockly als Top-Level-Projekt. Ist das so korrekt oder gehört der Level-Designer eher zu Blockly? Falls ja, sollte der Ordner in den `blockly`-Ordner verschoben werden.

- [x] Die ganzen doppelten Backticks sind quasi wirkungslos: Der erste Backtick macht eine Inline-Code-Umgebung auf, der zweite wieder zu. Ich habe das mal mit Code-Vorschlägen im Review korrigiert. Bitte anschließend nochmal mit `grep -r "``" *` schauen, ob noch irgendwo was schlummert ...

2024-10-11 11:49 UTC, cagix commented on blockly/build.gradle
> +  testImplementation supportDependencies.junit
```suggestion
  implementation project(':dungeon')
  
  // ANTLR version 4 for DSL Grammar
  antlr supportDependencies.antlr
  
  // JUnit 4 and Mockito for testing
  testImplementation supportDependencies.junit
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/usage.md
> +3. **Aktionen ausführen:** Nachdem die Blöcke platziert wurden, kann durch Drücken des ``Start``-Buttons der Code ausgeführt
```suggestion
3. **Aktionen ausführen:** Nachdem die Blöcke platziert wurden, kann durch Drücken des `Start`-Buttons der Code ausgeführt
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/usage.md
> +werden und der `Dungeon-Charakter` wird entsprechend der Logik bewegt. Der ``Start``-Button sorgt dafür, dass der gesamte
```suggestion
werden und der `Dungeon-Charakter` wird entsprechend der Logik bewegt. Der `Start`-Button sorgt dafür, dass der gesamte
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/usage.md
> +in dem Eingabe-Feld ``Verzögerung (in Sek.)`` eine Verzögerung nach jedem Schritt mitgegeben werden. Der Wert muss in
```suggestion
in dem Eingabe-Feld `Verzögerung (in Sek.)` eine Verzögerung nach jedem Schritt mitgegeben werden. Der Wert muss in
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/usage.md
> +4. **Programm unterbrechen**: Durch Drücken des ``Reset``-Buttons wird der `Dungeon-Charakter` an seine Startposition zurückgesetzt. Außerdem wird die
```suggestion
4. **Programm unterbrechen**: Durch Drücken des `Reset`-Buttons wird der `Dungeon-Charakter` an seine Startposition zurückgesetzt. Außerdem wird die
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/usage.md
> +4. **Programm unterbrechen**: Durch Drücken des ``Reset``-Buttons wird der `Dungeon-Charakter` an seine Startposition zurückgesetzt. Außerdem wird die
```suggestion
4. **Programm unterbrechen**: Durch Drücken des `Reset`-Buttons wird der `Dungeon-Charakter` an seine Startposition zurückgesetzt. Außerdem wird die
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/usage.md
> +5. **Programm Schritt-für-Schritt ausführen**: Mithilfe des ``Step``-Buttons ist es möglich, das Programm Schritt-für-Schritt
```suggestion
5. **Programm Schritt-für-Schritt ausführen**: Mithilfe des `Step`-Buttons ist es möglich, das Programm Schritt-für-Schritt
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +Blöcke mit Werten rein. Mit dem Befehl ``Outbox`` transportiert der Büroangestellte den obersten Block vom
```suggestion
Blöcke mit Werten rein. Mit dem Befehl `Outbox` transportiert der Büroangestellte den obersten Block vom
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +auch Ausnahmen, wie das Spiel ``Human Resource Machine``. Es ist einsteigerfreundlich und unabhängig von einer
```suggestion
auch Ausnahmen, wie das Spiel `Human Resource Machine`. Es ist einsteigerfreundlich und unabhängig von einer
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +Monster stellen eine zentrale Rolle in dem Visualisierungskonzept dar. Ähnlich wie die Blöcke bei ``Human Resource Machine``
```suggestion
Monster stellen eine zentrale Rolle in dem Visualisierungskonzept dar. Ähnlich wie die Blöcke bei `Human Resource Machine`
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +Bei langen Variablennamen werden die Zeichen, welche zu viel sind durch ein ``...`` ersetzt, damit sich die
```suggestion
Bei langen Variablennamen werden die Zeichen, welche zu viel sind durch ein `...` ersetzt, damit sich die
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +In der Denkblase werden zwei Buttons angezeigt auf denen ``AND`` steht. Die beiden booleschen Werte werden wieder durch
```suggestion
In der Denkblase werden zwei Buttons angezeigt auf denen `AND` steht. Die beiden booleschen Werte werden wieder durch
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +In der Denkblase werden erneut zwei Buttons angezeigt, auf denen dieses Mal jedoch ``OR`` steht. Wie bei ``AND`` läuft
```suggestion
In der Denkblase werden erneut zwei Buttons angezeigt, auf denen dieses Mal jedoch `OR` steht. Wie bei `AND` läuft
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +Es wird ein Button angezeigt auf dem ``NOT`` steht. Der Button leuchtet grün, wenn kein Monster auf dem Button steht.
```suggestion
Es wird ein Button angezeigt auf dem `NOT` steht. Der Button leuchtet grün, wenn kein Monster auf dem Button steht.
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +Eine Funktion wird über ein neues Item ``To-do-Liste`` abgebildet. Zu Beginn einer Funktion wird das Item ``To-do-Liste``
```suggestion
Eine Funktion wird über ein neues Item `To-do-Liste` abgebildet. Zu Beginn einer Funktion wird das Item `To-do-Liste`
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +``<Icon TODO-Liste>`` mit dem Text: ``To-do-Liste: 'Funktionsname' wird bearbeitet``. Wenn die Funktion beendet ist, wird
```suggestion
`<Icon TODO-Liste>` mit dem Text: `To-do-Liste: 'Funktionsname' wird bearbeitet`. Wenn die Funktion beendet ist, wird
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +``To-do-Liste: 'Funktionsname' abgeschlossen``.
```suggestion
`To-do-Liste: 'Funktionsname' abgeschlossen`.
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +hauptsächlich die folgenden Funktionen in der ``Server`` Klasse aufgerufen:
```suggestion
immer an derselben Stelle auf dem Bildschirm platziert sind. Da die Ausführung des Codes in der Klasse `Server`
geschieht, erhält die Klasse Server ein Objekt der Klasse `VariableHUD`. Die Klasse `Client` erstellt das Objekt
der Klasse `VariableHUD` und übergibt es an die `Server` Klasse. Auf dem `VariableHUD`-Objekt werden
hauptsächlich die folgenden Funktionen in der `Server` Klasse aufgerufen:
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +Klasse ``BlocklyHUD`` erbt. Es müssen die beiden Funktionen ``updateActors`` und ``createEntity`` implementiert werden.
```suggestion
Klasse `BlocklyHUD` erbt. Es müssen die beiden Funktionen `updateActors` und `createEntity` implementiert werden.
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +Die Funktion ``updateActors`` muss dabei genutzt werden, um die Größe des HUDs an die aktuelle Bildschirmgröße anzupassen.
```suggestion
Die Funktion `updateActors` muss dabei genutzt werden, um die Größe des HUDs an die aktuelle Bildschirmgröße anzupassen.
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +Die Funktion wird durch das ``HudBlocklySystem`` für alle Entitäten aufgerufen, welche eine ``BlocklyUIComponent``
```suggestion
Die Funktion wird durch das `HudBlocklySystem` für alle Entitäten aufgerufen, welche eine `BlocklyUIComponent`
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +besitzen. Die Funktion ``createEntity`` sollte eine Entität zurückgeben, welche die Komponente ``BlocklyUIComponent``
```suggestion
besitzen. Die Funktion `createEntity` sollte eine Entität zurückgeben, welche die Komponente `BlocklyUIComponent`
```

2024-10-11 11:49 UTC, cagix commented on blockly/doc/visualization_concept.md
> +besitzt. Der Konstruktor der ``BlocklyUIComponent`` Klasse erhält ein Objekt der Klasse ``BlocklyHUD``. Dort muss das
```suggestion
besitzt. Der Konstruktor der `BlocklyUIComponent` Klasse erhält ein Objekt der Klasse `BlocklyHUD`. Dort muss das
```

2024-10-11 11:49 UTC, cagix commented on blockly/frontend/src/api/api.ts
> +    */
??? Brauchen wir das noch oder kann das weg? Auskommentierter Code ist irgendwie immer schräg. Zumindest sollte ein Kommentar dran - besser aber weg, wenn wir es nicht mehr brauchen.

2024-10-11 11:49 UTC, cagix commented on blockly/src/level/ITickable.java
gibt es dieses interface nicht schon?

das müsste im dungeon sein (`contrib`)? dann bitte das nutzen und nicht hier als kopie einführen.

2024-10-11 11:56 UTC, cagix requested changes

2024-10-11 11:56 UTC, cagix commented on level-designer/README.md
> +"blockly" unter ``src/level/LevelParser`` zu finden.
```suggestion
"blockly" unter `src/level/LevelParser` zu finden.
```

2024-10-11 11:56 UTC, cagix commented on level-designer/README.md
> +generierten Dateien sind in dem Ordner ``dist_maps`` zu finden. In dieser Datei
```suggestion
generierten Dateien sind in dem Ordner `dist_maps` zu finden. In dieser Datei
```

2024-10-11 11:56 UTC, cagix commented on level-designer/README.md
> +kann, muss das Python-Skript ``build_level_file.py`` ausgeführt werden. Die
```suggestion
kann, muss das Python-Skript `build_level_file.py` ausgeführt werden. Die
```

2024-10-11 11:56 UTC, cagix commented on level-designer/README.md
> +muss dann in den Ordner ``src_maps`` kopiert werden.
```suggestion
muss dann in den Ordner `src_maps` kopiert werden.
```

2024-10-12 08:32 UTC, cagix requested changes

2024-10-12 08:32 UTC, cagix commented on settings.gradle
> +include 'game', 'dungeon', 'blockly', 'dojo-dungeon', 'devDungeon', 'level-designer'
@CodingJosh42  Ich würde den Level-Designer hier nicht aufnehmen - das ist ja kein Gradle-Projekt.

2024-10-14 18:28 UTC, CodingJosh42 commented on blockly/src/level/ITickable.java
@cagix Ich habe das Interface aus dem DevDungeon. Habe es jetzt bei Blockly gelöscht und eine Abhängigkeit zum DevDungeon hinzugefügt. Ich habe das ursprünglich nicht gemacht, um eine Abhängigkeit zu einem ganzen Projekt für ein Interface zu verhindern.

2024-10-15 15:35 UTC, cagix approved these changes
@CodingJosh42 👌🥳❤️🙏

2024-10-15 15:36 UTC, cagix commented
@CodingJosh42 Danke Dir!

2024-10-15 15:36 UTC, merged