[Thesis] Implementation der Dungine.
Dungeon-CampusMinden/Dungeon pull request #1652
Opened 2024-10-23 01:57 UTC by fwatermann

To be filled...

2024-10-23 06:04 UTC, cagix commented
@fwatermann Schau mal auf das Build-Log - ich glaube, an der Gradle-Konfiguration fehlt noch was. Und er beschwert sich über fehlende `@Override` in alten Klassen?

2024-10-23 06:05 UTC, cagix commented
@AMatutat Schau Dir das mal an :)  @fwatermann schlägt hier das Entfernen von libGDX vor und baut auf 3D um ...

2024-10-23 11:24 UTC, fwatermann commented
> @fwatermann Schau mal auf das Build-Log - ich glaube, an der Gradle-Konfiguration fehlt noch was. Und er beschwert sich über fehlende `@Override` in alten Klassen?

Whoops, da hat sich wohl eine Rumspielklasse eingeschlichen 🥴

2024-10-23 13:43 UTC, fwatermann commented
> @fwatermann Wenn Du schon dabei bist: Es wäre gut, wenn die ursprünglichen Beispiele und Klassen auch nach dem Merge noch funktionieren würden, also wenn es am besten da keine Änderungen gäbe und Du Deine Demo als neue Starter irgendwo reintust. Dann ist das Projekt tatsächlich unabhängig und @AMatutat kann in Ruhe überlegen, wann wir ggf. umsteigen :)
> 
> Das betrifft diese Änderungen:
> 
> * `dsl-ide-support-with-lsp/intellij-plugin/.run/Run IDE with Plugin.run.xml`: Das wird gelöscht?
> * `game/build.gradle`: Gut, das ist nur ein entfernter Kommentar. Aber gehört das wirklich hier mit rein?
> * `game/src/core/components/PlayerComponent.java`: Da ist ein Import verschwunden? Ich schätze, der wurde gebraucht? Hmmm.
> * `game/src/core/game/GameLoop.java`: Dito, einige Änderungen an den Importen.
> 
> Und die `settings.gradle` würde nach dem Merge auf einmal ein paar Subprojekte deaktivieren. Das war in der Bearbeitung für Dich sinnvoll, aber zum Merge würde ich das gern nur erweitern um Deine neuen Subprojekte :)

Hab die Dateien resettet. Das die Imports geändert sind, liegt an einer Einstellung in IntelliJ, wie Imports geschrieben werden. Die Standardeinstellung fasst ab einer definierten Anzahl an Imports aus dem selben Package diese zu `package.*` zusammen. Die Option ist bei mir deaktiviert (Settings > Editor > Code Style > Java > Imports > `Class count to use import with '*'`). Man könnte an dieser Stelle überlegen ob man das in die EditorConfig aufnimmt (`ij_java_class_count_to_use_import_on_demand`).

2024-10-23 14:29 UTC, cagix commented
> > @fwatermann Wenn Du schon dabei bist: Es wäre gut, wenn die ursprünglichen Beispiele und Klassen auch nach dem Merge noch funktionieren würden, also wenn es am besten da keine Änderungen gäbe und Du Deine Demo als neue Starter irgendwo reintust. Dann ist das Projekt tatsächlich unabhängig und @AMatutat kann in Ruhe überlegen, wann wir ggf. umsteigen :)
> > Das betrifft diese Änderungen:
> > 
> > * `dsl-ide-support-with-lsp/intellij-plugin/.run/Run IDE with Plugin.run.xml`: Das wird gelöscht?
> > * `game/build.gradle`: Gut, das ist nur ein entfernter Kommentar. Aber gehört das wirklich hier mit rein?
> > * `game/src/core/components/PlayerComponent.java`: Da ist ein Import verschwunden? Ich schätze, der wurde gebraucht? Hmmm.
> > * `game/src/core/game/GameLoop.java`: Dito, einige Änderungen an den Importen.
> > 
> > Und die `settings.gradle` würde nach dem Merge auf einmal ein paar Subprojekte deaktivieren. Das war in der Bearbeitung für Dich sinnvoll, aber zum Merge würde ich das gern nur erweitern um Deine neuen Subprojekte :)
> 
> Hab die Dateien resettet. 

Danke Dir :)


> Das die Imports geändert sind, liegt an einer Einstellung in IntelliJ, wie Imports geschrieben werden. Die Standardeinstellung fasst ab einer definierten Anzahl an Imports aus dem selben Package diese zu `package.*` zusammen. Die Option ist bei mir deaktiviert (Settings > Editor > Code Style > Java > Imports > `Class count to use import with '*'`). Man könnte an dieser Stelle überlegen ob man das in die EditorConfig aufnimmt (`ij_java_class_count_to_use_import_on_demand`).

Hmmm, wusste gar nicht, dass man über die EditorConfig darauf Einfluss nehmen kann? Hatte eher Richtung Checkstyle oder (besser) Spotless vermutet?

2024-10-23 14:42 UTC, cagix commented
@fwatermann Hmmm, es compiliert jetzt :)  Aber Spotless und Checkstyle sind beide noch nicht happy. Kannst Du bitte noch einmal Spotless über Deinen Code laufen lassen? Bei Checkstyle fehlt bestimmt nur irgendwo noch ein Javadoc, oder die erste Zeile entspricht vielleicht noch nicht den Konventionen (muss mit einem "." enden)?

2024-10-24 08:11 UTC, cagix commented
checks sind grün 🎉🥳

2024-10-24 13:42 UTC, cagix commented
@fwatermann Ich hab noch eine Idee. In Deiner Abschlussarbeit beschreibst Du ja die verschiedenen Teile der Dungine und vergleichst das mit dem ursprünglichen Projekten. Ich könnte mir das gut als Dokumentation unter `dungine/doc/` vorstellen. 

Was denkst Du? 

Afaik hattest Du ja mit dem Markdown-Template gearbeitet, oder? Da könntest Du das direkt rüberkopieren und das Hauptdokument nennst Du einfach `readme.md`, die anderen lässt Du so. Dann hätte das Subprojekt auch gleich noch etwas Doku dabei.

2024-10-28 15:20 UTC, AMatutat commented
@cagix hast du das auf Mac zum laufen bekommen? Ich scheitere an OpenGL

2024-11-06 11:53 UTC, cagix commented
> > @cagix hast du das auf Mac zum laufen bekommen? Ich scheitere an OpenGL
> 
> Das Problem sollte gefixt sein

@fwatermann @AMatutat Ich kriege es zumindest gebaut. Bei `./gradlew :dungine-demo:run` kommt das Startfenster mit der Auswahl: 

<img width="1392" alt="Screenshot 2024-11-06 at 12 52 20" src="https://github.com/user-attachments/assets/b3313a1f-0213-4158-8404-68f57820ef54">

Aber bei jedem Button (bis auf "Exit" :) stürzt das Mopped dann ab:

```
> Task :dungine-demo:run
[06.11.2024 12:51:15.573/GameWindow@main/INFO] Initialized GameWindow: Dungine
[06.11.2024 12:51:16.125/GameWindow@main/INFO] OpenGL Version: 4.1 Metal - 89.3
[06.11.2024 12:51:16.145/EventManager@main/DEBUG] Registered event handler for event type de.fwatermann.dungine.event.window.FrameBufferResizeEvent by dungine.state.StateMainMenu
[06.11.2024 12:51:16.287/Font@main/DEBUG] Font "Open Sans" is a monochrome font
[06.11.2024 12:51:16.287/Font@main/DEBUG] FontFace loaded: "Open Sans" with 1 faces [color: false]
[06.11.2024 12:51:16.383/Font@main/DEBUG] Font loaded in 102ms
[06.11.2024 12:51:16.386/Font@main/DEBUG] Font "JetBrains Mono" is a monochrome font
[06.11.2024 12:51:16.386/Font@main/DEBUG] FontFace loaded: "JetBrains Mono" with 1 faces [color: false]
[06.11.2024 12:51:16.418/Font@main/DEBUG] Font loaded in 33ms
[06.11.2024 12:51:16.421/EventManager@main/DEBUG] Registered event handler for event type de.fwatermann.dungine.event.window.FrameBufferResizeEvent by de.fwatermann.dungine.ui.UIRoot
[06.11.2024 12:51:16.422/EventManager@main/DEBUG] Registered event handler for event type de.fwatermann.dungine.event.input.MouseButtonEvent by de.fwatermann.dungine.ui.UIRoot
[06.11.2024 12:51:16.422/EventManager@main/DEBUG] Registered event handler for event type de.fwatermann.dungine.event.input.MouseScrollEvent by de.fwatermann.dungine.ui.UIRoot
[06.11.2024 12:51:16.428/ShaderProgram@main/INFO] Successfully linked shader program: 4
[06.11.2024 12:51:16.432/ShaderProgram@main/WARN] Uniform 'uCameraPosition' not found in shader program
[06.11.2024 12:51:16.433/ShaderProgram@main/WARN] Uniform 'uModel' not found in shader program
[06.11.2024 12:51:16.443/ShaderProgram@main/INFO] Successfully linked shader program: 7
[06.11.2024 12:51:16.443/ShaderProgram@main/WARN] Uniform 'uCameraPosition' not found in shader program
2024-11-06 12:51:16.464 java[3084:177411] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-06 12:51:16.464 java[3084:177411] +[IMKInputSession subclass]: chose IMKInputSession_Modern
[06.11.2024 12:51:16.480/EventManager@main/DEBUG] Registered static event handler for event type de.fwatermann.dungine.event.input.MouseButtonEvent by de.fwatermann.dungine.input.Mouse
[06.11.2024 12:51:18.026/EventManager@main/DEBUG] Registered event handler for event type de.fwatermann.dungine.event.window.FrameBufferResizeEvent by dungine.state.StatePlayerTest
[06.11.2024 12:51:18.027/EventManager@main/DEBUG] Unregistered de.fwatermann.dungine.event.window.FrameBufferResizeEvent handler for object of dungine.state.StateMainMenu [1713833639]
[06.11.2024 12:51:18.027/EventManager@main/DEBUG] Unregistered de.fwatermann.dungine.event.input.MouseScrollEvent handler for object of de.fwatermann.dungine.ui.UIRoot [252738640]
[06.11.2024 12:51:18.027/EventManager@main/DEBUG] Unregistered de.fwatermann.dungine.event.input.MouseButtonEvent handler for object of de.fwatermann.dungine.ui.UIRoot [252738640]
[06.11.2024 12:51:18.027/EventManager@main/DEBUG] Unregistered de.fwatermann.dungine.event.window.FrameBufferResizeEvent handler for object of de.fwatermann.dungine.ui.UIRoot [252738640]
[06.11.2024 12:51:18.061/ClasspathResource@main/DEBUG] Resolving relative path: /shaders/util/TextureAtlas.fsh (/shaders/level.fsh)
Exception in thread "main" de.fwatermann.dungine.exception.OpenGLException: Failed to link shader program: ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 33 samplers

        at de.fwatermann.dungine.graphics.shader.ShaderProgram.glInit(ShaderProgram.java:73)
        at de.fwatermann.dungine.graphics.shader.ShaderProgram.<init>(ShaderProgram.java:58)
        at dungine.level.OptimizedLevel.render(OptimizedLevel.java:78)
        at de.fwatermann.dungine.ecs.systems.RenderableSystem.lambda$update$4(RenderableSystem.java:96)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at de.fwatermann.dungine.ecs.systems.RenderableSystem.update(RenderableSystem.java:96)
        at de.fwatermann.dungine.ecs.ECS.lambda$executeSystems$9(ECS.java:262)
        at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1134)
        at de.fwatermann.dungine.ecs.ECS.executeSystems(ECS.java:257)
        at de.fwatermann.dungine.state.GameState.render(GameState.java:104)
        at de.fwatermann.dungine.window.GameWindow._renderLoop(GameWindow.java:342)
        at de.fwatermann.dungine.window.GameWindow._init(GameWindow.java:128)
        at de.fwatermann.dungine.window.GameWindow.start(GameWindow.java:604)
        at dungine.Main.main(Main.java:22)

```

2024-11-06 12:19 UTC, fwatermann commented
> > > @cagix hast du das auf Mac zum laufen bekommen? Ich scheitere an OpenGL
> > 
> > 
> > Das Problem sollte gefixt sein
> 
> @fwatermann @AMatutat Ich kriege es zumindest gebaut. Bei `./gradlew :dungine-demo:run` kommt das Startfenster mit der Auswahl:
> 
> <img alt="Screenshot 2024-11-06 at 12 52 20" width="1392" src="https://private-user-images.githubusercontent.com/20356276/383541858-b3313a1f-0213-4158-8404-68f57820ef54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4OTQ4NDQsIm5iZiI6MTczMDg5NDU0NCwicGF0aCI6Ii8yMDM1NjI3Ni8zODM1NDE4NTgtYjMzMTNhMWYtMDIxMy00MTU4LTg0MDQtNjhmNTc4MjBlZjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDEyMDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTVmODJiMzEzMTVhZTQ5Yjg5NGM1ODU0ZmIzNmYzOGQxYzg1YTQ5MzZkM2NlZGYxMzY0ZTVkZWJhOGE1NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KYB4POOt2OGpM2bDNpnPc9II9lUAnRIbJKNWg8rcZ8E">
> Aber bei jedem Button (bis auf "Exit" :) stürzt das Mopped dann ab.
> 
> Bei "Beleuchtung":
> Bei "CameraComponent":
> Bei "Erde, Mond & Sonne":
> Bei "PlayerComponent":
> Bei "3D-Level":

Die beiden Fehler sollten gefixt sein. Habe nur leider keinen Mac zum testen da :/

2024-11-06 13:00 UTC, cagix commented
@fwatermann du bist echt schnell! bist du sicher, dass du nicht im dungeon mal was machen willst? 

ich bin grad komplett unter wasser, hoffentlich kann ich das heute nochmal starten.

2024-11-06 14:09 UTC, cagix commented
> @cagix Die beiden Fehler sollten gefixt sein. Habe nur leider keinen Mac zum testen da :/

hmmm. gefixt insofern, dass jetzt in allem items die jvm hart abstürzt 🤣

das letzte, was vor dem absturz kommt, war `[06.11.2024 15:07:08.822/ClasspathResource@main/DEBUG] Resolving relative path: ../util/Animation.fsh (/shaders/3d/Sprite.fsh)` bzw. `[06.11.2024 15:07:16.613/Shader@main/DEBUG] Circular include detected: ../util/Material.fsh` ...

2024-11-18 14:32 UTC, cagix requested changes
Irgendwas klemmt auf macOS (ARM) mit der geladenen Bibliothek - die Java-VM stürzt hart ab. Entweder muss noch was an der Gradle-Konfiguration angepasst werden oder die Lib tut einfach nicht auf ARM? Dem muss noch nachgegangen werden (@cagix, @AMatutat).

Wir haben bei der Demo verabredet, dass im Doc-Ordner noch die relevanten Teile der BA als Markdown reinkommen (@fwatermann).

@fwatermann Du kannst die Literatur-Referenzen mit Pandoc auflösen: 

```
pandoc -s -t gfm -f markdown 
       -M lang=de-DE --metadata-file=metadata.yml 
       --citeproc -M bibliography=references.bib -M link-citations=true 
       md/INPUT1.md md/INPUT2.md md/INPUT3.md md/INPUT4.md 
       -o OUTPUT.md
``` 

... ggf. möchtest Du als letzte Überschrift noch ein `## Quellen` einfügen (das Verzeichnis wird nämlich einfach ans Ende des Dokuments gepackt).

2024-12-01 12:30 UTC, cagix commented
Mist. Auf einem Intel-Mac kommt nicht mal das Auswahlfenster hoch. Das Ding geht sofort mit einem java.lang.UnsatisfiedLinkError sterben ...

```
> Task :dungine-demo:run
[01.12.2024 13:27:57.425/GameWindow@main/INFO] Initialized GameWindow: Dungine
[01.12.2024 13:28:00.021/GameWindow@main/INFO] OpenGL Version: 4.1 INTEL-23.0.2
[01.12.2024 13:28:00.065/EventManager@main/DEBUG] Registered event handler for event type de.fwatermann.dungine.event.window.FrameBufferResizeEvent by dungine.state.StateMainMenu
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /var/folders/1c/b8hxgmzd01x4gfb415b96tqc0000gn/T/lwjgl_cagix/3.3.3-snapshot/x64/libfreetype.dylib(error = null)
        at org.lwjgl.system.macosx.MacOSXLibraryDL.loadLibrary(MacOSXLibraryDL.java:33)
        at org.lwjgl.system.macosx.MacOSXLibraryDL.<init>(MacOSXLibraryDL.java:20)
        at org.lwjgl.system.macosx.MacOSXLibrary.create(MacOSXLibrary.java:27)
        at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:130)
        at org.lwjgl.system.Library.loadNative(Library.java:382)
        at org.lwjgl.system.Library.loadNativeFromLibraryPath(Library.java:371)
        at org.lwjgl.system.Library.loadNative(Library.java:285)
        at org.lwjgl.system.Library.loadNative(Library.java:236)
        at org.lwjgl.util.freetype.FreeType.<clinit>(FreeType.java:44)
        at de.fwatermann.dungine.graphics.text.Font.<clinit>(Font.java:52)
        at dungine.state.StateMainMenu.init(StateMainMenu.java:47)
        at de.fwatermann.dungine.window.GameWindow.lambda$setState$11(GameWindow.java:750)
        at de.fwatermann.dungine.window.GameWindow.lambda$_renderLoop$9(GameWindow.java:357)
        at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037)
        at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054)
        at de.fwatermann.dungine.window.GameWindow._renderLoop(GameWindow.java:357)
        at de.fwatermann.dungine.window.GameWindow._init(GameWindow.java:128)
        at de.fwatermann.dungine.window.GameWindow.start(GameWindow.java:604)
        at dungine.Main.main(Main.java:22)
```

2024-12-01 12:42 UTC, merged

2024-12-03 13:19 UTC, AMatutat commented
> @AMatutat Ich kriege das weder unter Intel-Mac noch M1-Mac zum Laufen. Das scheint aber vor allem ein Konfigurationsproblem zu sein, der Code läuft aber tatsächlich, zumindest unter Windows (@fwatermann hatte @bcg7 und mir nochmal ne Demo gezeigt). @bcg7 wollte eigentlich auch nochmal schauen, ob es auch unter Linux tut, aber vermutlich hat sie keine Zeit.

Hmm okay intel-mac hätte ich jetzt eigentlich erwartet.... 

> Ich finde das Ergebnis trotzdem sehr spannend und würde es gern zumindest als Konzeptstudie mergen. Da sind neben dem direkten Einsatz von LWJGL/Verzicht auf libGDX viele interessante Ideen drin, die den Code im "alten" Dungeon deutlich verbessern könnten.

Gibts Fotos oder so? Hab das noch gar nicht gesehen

2024-12-03 15:27 UTC, cagix commented
> Gibts Fotos oder so? Hab das noch gar nicht gesehen

Leider nein, auch kein Screencast. Sieht erstmal so aus wie unser Dungeon (selbes Tile-Set), aber Du kannst halt beliebig hoch und runter ... und da, wo die Tiles nicht hinkommen, sieht es aus wie das Holodeck vor dem Start 😃